#!/bin/bash

#
# Copyright (c) 2020 ALİ GÜNGÖR (aligng1620@gmail.com)
# This software and all associated files are licensed under GPL-3.0.
#

java -cp "build/ueransim-release.jar:build/*:build/lib/*" tr.havelsan.ueransim.app.app.entry.AgentApp $@