#!/bin/bash

#
# This file is a part of UERANSIM open source project.
# Copyright (c) 2021 ALİ GÜNGÖR, Havelsan.
#
# The software and all associated files are licensed under GPL-3.0
# and subject to the terms and conditions defined in LICENSE file.
#

if [ -z "$1" ]
  then
    echo "No IP address supplied"
    exit
fi

addr=$1
shift

LD_PRELOAD=./build/libue-binder.so UE_BIND_ADDR=$addr $@