/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_VarResumeMAC_Input_H_
#define	_ASN_RRC_VarResumeMAC_Input_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_RRC_PhysCellId.h"
#include "ASN_RRC_CellIdentity.h"
#include "ASN_RRC_RNTI-Value.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ASN_RRC_VarResumeMAC-Input */
typedef struct ASN_RRC_VarResumeMAC_Input {
	ASN_RRC_PhysCellId_t	 sourcePhysCellId;
	ASN_RRC_CellIdentity_t	 targetCellIdentity;
	ASN_RRC_RNTI_Value_t	 source_c_RNTI;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_VarResumeMAC_Input_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_VarResumeMAC_Input;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_VarResumeMAC_Input_H_ */
#include <asn_internal.h>
