/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_UL_DCCH_MessageType_H_
#define	_ASN_RRC_UL_DCCH_MessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_UL_DCCH_MessageType_PR {
	ASN_RRC_UL_DCCH_MessageType_PR_NOTHING,	/* No components present */
	ASN_RRC_UL_DCCH_MessageType_PR_c1,
	ASN_RRC_UL_DCCH_MessageType_PR_messageClassExtension
} ASN_RRC_UL_DCCH_MessageType_PR;
typedef enum ASN_RRC_UL_DCCH_MessageType__c1_PR {
	ASN_RRC_UL_DCCH_MessageType__c1_PR_NOTHING,	/* No components present */
	ASN_RRC_UL_DCCH_MessageType__c1_PR_measurementReport,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_rrcReconfigurationComplete,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_rrcSetupComplete,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_rrcReestablishmentComplete,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_rrcResumeComplete,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_securityModeComplete,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_securityModeFailure,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_ulInformationTransfer,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_locationMeasurementIndication,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_ueCapabilityInformation,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_counterCheckResponse,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_ueAssistanceInformation,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_failureInformation,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_ulInformationTransferMRDC,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_scgFailureInformation,
	ASN_RRC_UL_DCCH_MessageType__c1_PR_scgFailureInformationEUTRA
} ASN_RRC_UL_DCCH_MessageType__c1_PR;

/* Forward declarations */
struct ASN_RRC_MeasurementReport;
struct ASN_RRC_RRCReconfigurationComplete;
struct ASN_RRC_RRCSetupComplete;
struct ASN_RRC_RRCReestablishmentComplete;
struct ASN_RRC_RRCResumeComplete;
struct ASN_RRC_SecurityModeComplete;
struct ASN_RRC_SecurityModeFailure;
struct ASN_RRC_ULInformationTransfer;
struct ASN_RRC_LocationMeasurementIndication;
struct ASN_RRC_UECapabilityInformation;
struct ASN_RRC_CounterCheckResponse;
struct ASN_RRC_UEAssistanceInformation;
struct ASN_RRC_FailureInformation;
struct ASN_RRC_ULInformationTransferMRDC;
struct ASN_RRC_SCGFailureInformation;
struct ASN_RRC_SCGFailureInformationEUTRA;

/* ASN_RRC_UL-DCCH-MessageType */
typedef struct ASN_RRC_UL_DCCH_MessageType {
	ASN_RRC_UL_DCCH_MessageType_PR present;
	union ASN_RRC_UL_DCCH_MessageType_u {
		struct ASN_RRC_UL_DCCH_MessageType__c1 {
			ASN_RRC_UL_DCCH_MessageType__c1_PR present;
			union ASN_RRC_UL_DCCH_MessageType__ASN_RRC_c1_u {
				struct ASN_RRC_MeasurementReport	*measurementReport;
				struct ASN_RRC_RRCReconfigurationComplete	*rrcReconfigurationComplete;
				struct ASN_RRC_RRCSetupComplete	*rrcSetupComplete;
				struct ASN_RRC_RRCReestablishmentComplete	*rrcReestablishmentComplete;
				struct ASN_RRC_RRCResumeComplete	*rrcResumeComplete;
				struct ASN_RRC_SecurityModeComplete	*securityModeComplete;
				struct ASN_RRC_SecurityModeFailure	*securityModeFailure;
				struct ASN_RRC_ULInformationTransfer	*ulInformationTransfer;
				struct ASN_RRC_LocationMeasurementIndication	*locationMeasurementIndication;
				struct ASN_RRC_UECapabilityInformation	*ueCapabilityInformation;
				struct ASN_RRC_CounterCheckResponse	*counterCheckResponse;
				struct ASN_RRC_UEAssistanceInformation	*ueAssistanceInformation;
				struct ASN_RRC_FailureInformation	*failureInformation;
				struct ASN_RRC_ULInformationTransferMRDC	*ulInformationTransferMRDC;
				struct ASN_RRC_SCGFailureInformation	*scgFailureInformation;
				struct ASN_RRC_SCGFailureInformationEUTRA	*scgFailureInformationEUTRA;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *c1;
		struct ASN_RRC_UL_DCCH_MessageType__messageClassExtension {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *messageClassExtension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_UL_DCCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_UL_DCCH_MessageType;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_UL_DCCH_MessageType_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_UL_DCCH_MessageType_1[2];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_UL_DCCH_MessageType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_UL_DCCH_MessageType_H_ */
#include <asn_internal.h>
