/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_TDD_UL_DL_SlotConfig_H_
#define	_ASN_RRC_TDD_UL_DL_SlotConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_RRC_TDD-UL-DL-SlotIndex.h"
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_TDD_UL_DL_SlotConfig__symbols_PR {
	ASN_RRC_TDD_UL_DL_SlotConfig__symbols_PR_NOTHING,	/* No components present */
	ASN_RRC_TDD_UL_DL_SlotConfig__symbols_PR_allDownlink,
	ASN_RRC_TDD_UL_DL_SlotConfig__symbols_PR_allUplink,
	ASN_RRC_TDD_UL_DL_SlotConfig__symbols_PR_explicit
} ASN_RRC_TDD_UL_DL_SlotConfig__symbols_PR;

/* ASN_RRC_TDD-UL-DL-SlotConfig */
typedef struct ASN_RRC_TDD_UL_DL_SlotConfig {
	ASN_RRC_TDD_UL_DL_SlotIndex_t	 slotIndex;
	struct ASN_RRC_TDD_UL_DL_SlotConfig__symbols {
		ASN_RRC_TDD_UL_DL_SlotConfig__symbols_PR present;
		union ASN_RRC_TDD_UL_DL_SlotConfig__ASN_RRC_symbols_u {
			NULL_t	 allDownlink;
			NULL_t	 allUplink;
			struct ASN_RRC_TDD_UL_DL_SlotConfig__symbols__explicit {
				long	*nrofDownlinkSymbols;	/* OPTIONAL */
				long	*nrofUplinkSymbols;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *Explicit;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} symbols;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_TDD_UL_DL_SlotConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_TDD_UL_DL_SlotConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_TDD_UL_DL_SlotConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_TDD_UL_DL_SlotConfig_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_TDD_UL_DL_SlotConfig_H_ */
#include <asn_internal.h>
