/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#include "ASN_RRC_CellsToAddMod.h"

asn_TYPE_member_t asn_MBR_ASN_RRC_CellsToAddMod_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CellsToAddMod, physCellId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_PhysCellId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"physCellId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_CellsToAddMod, cellIndividualOffset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_Q_OffsetRangeList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellIndividualOffset"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_CellsToAddMod_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_CellsToAddMod_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physCellId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cellIndividualOffset */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_CellsToAddMod_specs_1 = {
	sizeof(struct ASN_RRC_CellsToAddMod),
	offsetof(struct ASN_RRC_CellsToAddMod, _asn_ctx),
	asn_MAP_ASN_RRC_CellsToAddMod_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_CellsToAddMod = {
	"CellsToAddMod",
	"CellsToAddMod",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_CellsToAddMod_tags_1,
	sizeof(asn_DEF_ASN_RRC_CellsToAddMod_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CellsToAddMod_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_CellsToAddMod_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_CellsToAddMod_tags_1)
		/sizeof(asn_DEF_ASN_RRC_CellsToAddMod_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_CellsToAddMod_1,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_CellsToAddMod_specs_1	/* Additional specs */
};

