/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_PollByte_H_
#define	_ASN_RRC_PollByte_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_PollByte {
	ASN_RRC_PollByte_kB1	= 0,
	ASN_RRC_PollByte_kB2	= 1,
	ASN_RRC_PollByte_kB5	= 2,
	ASN_RRC_PollByte_kB8	= 3,
	ASN_RRC_PollByte_kB10	= 4,
	ASN_RRC_PollByte_kB15	= 5,
	ASN_RRC_PollByte_kB25	= 6,
	ASN_RRC_PollByte_kB50	= 7,
	ASN_RRC_PollByte_kB75	= 8,
	ASN_RRC_PollByte_kB100	= 9,
	ASN_RRC_PollByte_kB125	= 10,
	ASN_RRC_PollByte_kB250	= 11,
	ASN_RRC_PollByte_kB375	= 12,
	ASN_RRC_PollByte_kB500	= 13,
	ASN_RRC_PollByte_kB750	= 14,
	ASN_RRC_PollByte_kB1000	= 15,
	ASN_RRC_PollByte_kB1250	= 16,
	ASN_RRC_PollByte_kB1500	= 17,
	ASN_RRC_PollByte_kB2000	= 18,
	ASN_RRC_PollByte_kB3000	= 19,
	ASN_RRC_PollByte_kB4000	= 20,
	ASN_RRC_PollByte_kB4500	= 21,
	ASN_RRC_PollByte_kB5000	= 22,
	ASN_RRC_PollByte_kB5500	= 23,
	ASN_RRC_PollByte_kB6000	= 24,
	ASN_RRC_PollByte_kB6500	= 25,
	ASN_RRC_PollByte_kB7000	= 26,
	ASN_RRC_PollByte_kB7500	= 27,
	ASN_RRC_PollByte_mB8	= 28,
	ASN_RRC_PollByte_mB9	= 29,
	ASN_RRC_PollByte_mB10	= 30,
	ASN_RRC_PollByte_mB11	= 31,
	ASN_RRC_PollByte_mB12	= 32,
	ASN_RRC_PollByte_mB13	= 33,
	ASN_RRC_PollByte_mB14	= 34,
	ASN_RRC_PollByte_mB15	= 35,
	ASN_RRC_PollByte_mB16	= 36,
	ASN_RRC_PollByte_mB17	= 37,
	ASN_RRC_PollByte_mB18	= 38,
	ASN_RRC_PollByte_mB20	= 39,
	ASN_RRC_PollByte_mB25	= 40,
	ASN_RRC_PollByte_mB30	= 41,
	ASN_RRC_PollByte_mB40	= 42,
	ASN_RRC_PollByte_infinity	= 43,
	ASN_RRC_PollByte_spare20	= 44,
	ASN_RRC_PollByte_spare19	= 45,
	ASN_RRC_PollByte_spare18	= 46,
	ASN_RRC_PollByte_spare17	= 47,
	ASN_RRC_PollByte_spare16	= 48,
	ASN_RRC_PollByte_spare15	= 49,
	ASN_RRC_PollByte_spare14	= 50,
	ASN_RRC_PollByte_spare13	= 51,
	ASN_RRC_PollByte_spare12	= 52,
	ASN_RRC_PollByte_spare11	= 53,
	ASN_RRC_PollByte_spare10	= 54,
	ASN_RRC_PollByte_spare9	= 55,
	ASN_RRC_PollByte_spare8	= 56,
	ASN_RRC_PollByte_spare7	= 57,
	ASN_RRC_PollByte_spare6	= 58,
	ASN_RRC_PollByte_spare5	= 59,
	ASN_RRC_PollByte_spare4	= 60,
	ASN_RRC_PollByte_spare3	= 61,
	ASN_RRC_PollByte_spare2	= 62,
	ASN_RRC_PollByte_spare1	= 63
} e_ASN_RRC_PollByte;

/* ASN_RRC_PollByte */
typedef long	 ASN_RRC_PollByte_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_RRC_PollByte_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_PollByte;
extern const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_PollByte_specs_1;
asn_struct_free_f ASN_RRC_PollByte_free;
asn_struct_print_f ASN_RRC_PollByte_print;
asn_constr_check_f ASN_RRC_PollByte_constraint;
ber_type_decoder_f ASN_RRC_PollByte_decode_ber;
der_type_encoder_f ASN_RRC_PollByte_encode_der;
xer_type_decoder_f ASN_RRC_PollByte_decode_xer;
xer_type_encoder_f ASN_RRC_PollByte_encode_xer;
per_type_decoder_f ASN_RRC_PollByte_decode_uper;
per_type_encoder_f ASN_RRC_PollByte_encode_uper;
per_type_decoder_f ASN_RRC_PollByte_decode_aper;
per_type_encoder_f ASN_RRC_PollByte_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_PollByte_H_ */
#include <asn_internal.h>
