/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_SpatialRelations_H_
#define	_ASN_RRC_SpatialRelations_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations {
	ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations_n4	= 0,
	ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations_n8	= 1,
	ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations_n16	= 2,
	ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations_n32	= 3,
	ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations_n64	= 4,
	ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations_n96	= 5
} e_ASN_RRC_SpatialRelations__maxNumberConfiguredSpatialRelations;
typedef enum ASN_RRC_SpatialRelations__maxNumberActiveSpatialRelations {
	ASN_RRC_SpatialRelations__maxNumberActiveSpatialRelations_n1	= 0,
	ASN_RRC_SpatialRelations__maxNumberActiveSpatialRelations_n2	= 1,
	ASN_RRC_SpatialRelations__maxNumberActiveSpatialRelations_n4	= 2,
	ASN_RRC_SpatialRelations__maxNumberActiveSpatialRelations_n8	= 3,
	ASN_RRC_SpatialRelations__maxNumberActiveSpatialRelations_n14	= 4
} e_ASN_RRC_SpatialRelations__maxNumberActiveSpatialRelations;
typedef enum ASN_RRC_SpatialRelations__additionalActiveSpatialRelationPUCCH {
	ASN_RRC_SpatialRelations__additionalActiveSpatialRelationPUCCH_supported	= 0
} e_ASN_RRC_SpatialRelations__additionalActiveSpatialRelationPUCCH;
typedef enum ASN_RRC_SpatialRelations__maxNumberDL_RS_QCL_TypeD {
	ASN_RRC_SpatialRelations__maxNumberDL_RS_QCL_TypeD_n1	= 0,
	ASN_RRC_SpatialRelations__maxNumberDL_RS_QCL_TypeD_n2	= 1,
	ASN_RRC_SpatialRelations__maxNumberDL_RS_QCL_TypeD_n4	= 2,
	ASN_RRC_SpatialRelations__maxNumberDL_RS_QCL_TypeD_n8	= 3,
	ASN_RRC_SpatialRelations__maxNumberDL_RS_QCL_TypeD_n14	= 4
} e_ASN_RRC_SpatialRelations__maxNumberDL_RS_QCL_TypeD;

/* ASN_RRC_SpatialRelations */
typedef struct ASN_RRC_SpatialRelations {
	long	 maxNumberConfiguredSpatialRelations;
	long	 maxNumberActiveSpatialRelations;
	long	*additionalActiveSpatialRelationPUCCH;	/* OPTIONAL */
	long	 maxNumberDL_RS_QCL_TypeD;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SpatialRelations_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberConfiguredSpatialRelations_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberActiveSpatialRelations_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_additionalActiveSpatialRelationPUCCH_15;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberDL_RS_QCL_TypeD_17;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SpatialRelations;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SpatialRelations_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SpatialRelations_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SpatialRelations_H_ */
#include <asn_internal.h>
