/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#include "ASN_RRC_MeasResults.h"

#include "ASN_RRC_MeasResultListNR.h"
#include "ASN_RRC_MeasResultListEUTRA.h"
#include "ASN_RRC_MeasResultServFreqListEUTRA-SCG.h"
#include "ASN_RRC_MeasResultServFreqListNR-SCG.h"
#include "ASN_RRC_MeasResultSFTD-EUTRA.h"
#include "ASN_RRC_MeasResultCellSFTD-NR.h"
static asn_per_constraints_t asn_PER_type_ASN_RRC_measResultNeighCells_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_measResultNeighCells_4[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_MeasResults__measResultNeighCells, choice.measResultListNR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasResultListNR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListNR"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_MeasResults__measResultNeighCells, choice.measResultListEUTRA),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasResultListEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultListEUTRA"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_measResultNeighCells_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measResultListNR */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* measResultListEUTRA */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_measResultNeighCells_specs_4 = {
	sizeof(struct ASN_RRC_MeasResults__measResultNeighCells),
	offsetof(struct ASN_RRC_MeasResults__measResultNeighCells, _asn_ctx),
	offsetof(struct ASN_RRC_MeasResults__measResultNeighCells, present),
	sizeof(((struct ASN_RRC_MeasResults__measResultNeighCells *)0)->present),
	asn_MAP_ASN_RRC_measResultNeighCells_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_measResultNeighCells_4 = {
	"measResultNeighCells",
	"measResultNeighCells",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_measResultNeighCells_constr_4, CHOICE_constraint },
	asn_MBR_ASN_RRC_measResultNeighCells_4,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_measResultNeighCells_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_ext1_9[] = {
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_MeasResults__ext1, measResultServFreqListEUTRA_SCG),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasResultServFreqListEUTRA_SCG,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultServFreqListEUTRA-SCG"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_MeasResults__ext1, measResultServFreqListNR_SCG),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasResultServFreqListNR_SCG,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultServFreqListNR-SCG"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_MeasResults__ext1, measResultSFTD_EUTRA),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasResultSFTD_EUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultSFTD-EUTRA"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_MeasResults__ext1, measResultSFTD_NR),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasResultCellSFTD_NR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultSFTD-NR"
		},
};
static const int asn_MAP_ASN_RRC_ext1_oms_9[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_ext1_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_ext1_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measResultServFreqListEUTRA-SCG */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultServFreqListNR-SCG */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* measResultSFTD-EUTRA */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* measResultSFTD-NR */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_ext1_specs_9 = {
	sizeof(struct ASN_RRC_MeasResults__ext1),
	offsetof(struct ASN_RRC_MeasResults__ext1, _asn_ctx),
	asn_MAP_ASN_RRC_ext1_tag2el_9,
	4,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_ext1_oms_9,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ext1_9 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_ext1_tags_9,
	sizeof(asn_DEF_ASN_RRC_ext1_tags_9)
		/sizeof(asn_DEF_ASN_RRC_ext1_tags_9[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_ext1_tags_9,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_ext1_tags_9)
		/sizeof(asn_DEF_ASN_RRC_ext1_tags_9[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_ext1_9,
	4,	/* Elements count */
	&asn_SPC_ASN_RRC_ext1_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_MeasResults_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_MeasResults, measId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_MeasResults, measResultServingMOList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_MeasResultServMOList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultServingMOList"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_MeasResults, measResultNeighCells),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_measResultNeighCells_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultNeighCells"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_MeasResults, ext1),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ASN_RRC_ext1_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext1"
		},
};
static const int asn_MAP_ASN_RRC_MeasResults_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_MeasResults_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_MeasResults_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultServingMOList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* measResultNeighCells */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ext1 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_MeasResults_specs_1 = {
	sizeof(struct ASN_RRC_MeasResults),
	offsetof(struct ASN_RRC_MeasResults, _asn_ctx),
	asn_MAP_ASN_RRC_MeasResults_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_MeasResults_oms_1,	/* Optional members */
	1, 1,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_MeasResults = {
	"MeasResults",
	"MeasResults",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_MeasResults_tags_1,
	sizeof(asn_DEF_ASN_RRC_MeasResults_tags_1)
		/sizeof(asn_DEF_ASN_RRC_MeasResults_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_MeasResults_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_MeasResults_tags_1)
		/sizeof(asn_DEF_ASN_RRC_MeasResults_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_MeasResults_1,
	4,	/* Elements count */
	&asn_SPC_ASN_RRC_MeasResults_specs_1	/* Additional specs */
};

