/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_PUCCH_PowerControl_H_
#define	_ASN_RRC_PUCCH_PowerControl_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_PUCCH_PowerControl__twoPUCCH_PC_AdjustmentStates {
	ASN_RRC_PUCCH_PowerControl__twoPUCCH_PC_AdjustmentStates_twoStates	= 0
} e_ASN_RRC_PUCCH_PowerControl__twoPUCCH_PC_AdjustmentStates;

/* Forward declarations */
struct ASN_RRC_P0_PUCCH;
struct ASN_RRC_PUCCH_PathlossReferenceRS;

/* ASN_RRC_PUCCH-PowerControl */
typedef struct ASN_RRC_PUCCH_PowerControl {
	long	*deltaF_PUCCH_f0;	/* OPTIONAL */
	long	*deltaF_PUCCH_f1;	/* OPTIONAL */
	long	*deltaF_PUCCH_f2;	/* OPTIONAL */
	long	*deltaF_PUCCH_f3;	/* OPTIONAL */
	long	*deltaF_PUCCH_f4;	/* OPTIONAL */
	struct ASN_RRC_PUCCH_PowerControl__p0_Set {
		A_SEQUENCE_OF(struct ASN_RRC_P0_PUCCH) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *p0_Set;
	struct ASN_RRC_PUCCH_PowerControl__pathlossReferenceRSs {
		A_SEQUENCE_OF(struct ASN_RRC_PUCCH_PathlossReferenceRS) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pathlossReferenceRSs;
	long	*twoPUCCH_PC_AdjustmentStates;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_PUCCH_PowerControl_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_twoPUCCH_PC_AdjustmentStates_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_PUCCH_PowerControl;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_PUCCH_PowerControl_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_PUCCH_PowerControl_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_PUCCH_PowerControl_H_ */
#include <asn_internal.h>
