/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#include "ASN_RRC_LocationMeasurementInfo.h"

#include "ASN_RRC_EUTRA-RSTD-InfoList.h"
asn_per_constraints_t asn_PER_type_ASN_RRC_LocationMeasurementInfo_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ASN_RRC_LocationMeasurementInfo_1[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_LocationMeasurementInfo, choice.eutra_RSTD),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_EUTRA_RSTD_InfoList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-RSTD"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_LocationMeasurementInfo, choice.eutra_FineTimingDetection),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-FineTimingDetection"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_LocationMeasurementInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eutra-RSTD */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eutra-FineTimingDetection */
};
asn_CHOICE_specifics_t asn_SPC_ASN_RRC_LocationMeasurementInfo_specs_1 = {
	sizeof(struct ASN_RRC_LocationMeasurementInfo),
	offsetof(struct ASN_RRC_LocationMeasurementInfo, _asn_ctx),
	offsetof(struct ASN_RRC_LocationMeasurementInfo, present),
	sizeof(((struct ASN_RRC_LocationMeasurementInfo *)0)->present),
	asn_MAP_ASN_RRC_LocationMeasurementInfo_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_LocationMeasurementInfo = {
	"LocationMeasurementInfo",
	"LocationMeasurementInfo",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_LocationMeasurementInfo_constr_1, CHOICE_constraint },
	asn_MBR_ASN_RRC_LocationMeasurementInfo_1,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_LocationMeasurementInfo_specs_1	/* Additional specs */
};

