/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_UL_CCCH_MessageType_H_
#define	_ASN_RRC_UL_CCCH_MessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_UL_CCCH_MessageType_PR {
	ASN_RRC_UL_CCCH_MessageType_PR_NOTHING,	/* No components present */
	ASN_RRC_UL_CCCH_MessageType_PR_c1,
	ASN_RRC_UL_CCCH_MessageType_PR_messageClassExtension
} ASN_RRC_UL_CCCH_MessageType_PR;
typedef enum ASN_RRC_UL_CCCH_MessageType__c1_PR {
	ASN_RRC_UL_CCCH_MessageType__c1_PR_NOTHING,	/* No components present */
	ASN_RRC_UL_CCCH_MessageType__c1_PR_rrcSetupRequest,
	ASN_RRC_UL_CCCH_MessageType__c1_PR_rrcResumeRequest,
	ASN_RRC_UL_CCCH_MessageType__c1_PR_rrcReestablishmentRequest,
	ASN_RRC_UL_CCCH_MessageType__c1_PR_rrcSystemInfoRequest
} ASN_RRC_UL_CCCH_MessageType__c1_PR;

/* Forward declarations */
struct ASN_RRC_RRCSetupRequest;
struct ASN_RRC_RRCResumeRequest;
struct ASN_RRC_RRCReestablishmentRequest;
struct ASN_RRC_RRCSystemInfoRequest;

/* ASN_RRC_UL-CCCH-MessageType */
typedef struct ASN_RRC_UL_CCCH_MessageType {
	ASN_RRC_UL_CCCH_MessageType_PR present;
	union ASN_RRC_UL_CCCH_MessageType_u {
		struct ASN_RRC_UL_CCCH_MessageType__c1 {
			ASN_RRC_UL_CCCH_MessageType__c1_PR present;
			union ASN_RRC_UL_CCCH_MessageType__ASN_RRC_c1_u {
				struct ASN_RRC_RRCSetupRequest	*rrcSetupRequest;
				struct ASN_RRC_RRCResumeRequest	*rrcResumeRequest;
				struct ASN_RRC_RRCReestablishmentRequest	*rrcReestablishmentRequest;
				struct ASN_RRC_RRCSystemInfoRequest	*rrcSystemInfoRequest;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *c1;
		struct ASN_RRC_UL_CCCH_MessageType__messageClassExtension {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *messageClassExtension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_UL_CCCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_UL_CCCH_MessageType;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_UL_CCCH_MessageType_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_UL_CCCH_MessageType_1[2];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_UL_CCCH_MessageType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_UL_CCCH_MessageType_H_ */
#include <asn_internal.h>
