/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#include "ASN_RRC_SearchSpace.h"

static int
memb_ASN_RRC_sl2_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl4_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl5_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 4)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl8_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl10_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl16_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl20_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 19)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl40_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 39)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl80_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 79)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl160_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 159)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl320_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 319)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl640_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 639)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl1280_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1279)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_sl2560_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2559)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_ASN_RRC_duration_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 2 && value <= 2559)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ASN_RRC_monitoringSymbolsWithinSlot_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 14)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl2_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl4_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl5_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl8_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl10_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl16_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl20_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  19 }	/* (0..19) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl40_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  39 }	/* (0..39) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl80_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  79 }	/* (0..79) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl160_constr_15 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  159 }	/* (0..159) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl320_constr_16 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 9,  9,  0,  319 }	/* (0..319) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl640_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 10,  10,  0,  639 }	/* (0..639) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl1280_constr_18 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 11,  11,  0,  1279 }	/* (0..1279) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_sl2560_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 12,  12,  0,  2559 }	/* (0..2559) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_monitoringSlotPeriodicityAndOffset_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  14 }	/* (0..14) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel1_constr_23 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel2_constr_32 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel4_constr_41 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel8_constr_50 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel16_constr_59 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel1_constr_74 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel2_constr_77 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel4_constr_80 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel8_constr_83 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_aggregationLevel16_constr_86 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_dummy1_constr_95 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_dummy2_constr_104 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_dci_Formats_constr_109 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ASN_RRC_searchSpaceType_constr_68 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_duration_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 12,  12,  2,  2559 }	/* (2..2559) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ASN_RRC_monitoringSymbolsWithinSlot_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  14,  14 }	/* (SIZE(14..14)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ASN_RRC_monitoringSlotPeriodicityAndOffset_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sl1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl2_constr_6,  memb_ASN_RRC_sl2_constraint_4 },
		0, 0, /* No default value */
		"sl2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl4),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl4_constr_7,  memb_ASN_RRC_sl4_constraint_4 },
		0, 0, /* No default value */
		"sl4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl5),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl5_constr_8,  memb_ASN_RRC_sl5_constraint_4 },
		0, 0, /* No default value */
		"sl5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl8),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl8_constr_9,  memb_ASN_RRC_sl8_constraint_4 },
		0, 0, /* No default value */
		"sl8"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl10),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl10_constr_10,  memb_ASN_RRC_sl10_constraint_4 },
		0, 0, /* No default value */
		"sl10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl16),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl16_constr_11,  memb_ASN_RRC_sl16_constraint_4 },
		0, 0, /* No default value */
		"sl16"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl20),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl20_constr_12,  memb_ASN_RRC_sl20_constraint_4 },
		0, 0, /* No default value */
		"sl20"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl40),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl40_constr_13,  memb_ASN_RRC_sl40_constraint_4 },
		0, 0, /* No default value */
		"sl40"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl80),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl80_constr_14,  memb_ASN_RRC_sl80_constraint_4 },
		0, 0, /* No default value */
		"sl80"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl160),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl160_constr_15,  memb_ASN_RRC_sl160_constraint_4 },
		0, 0, /* No default value */
		"sl160"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl320),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl320_constr_16,  memb_ASN_RRC_sl320_constraint_4 },
		0, 0, /* No default value */
		"sl320"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl640),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl640_constr_17,  memb_ASN_RRC_sl640_constraint_4 },
		0, 0, /* No default value */
		"sl640"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl1280),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl1280_constr_18,  memb_ASN_RRC_sl1280_constraint_4 },
		0, 0, /* No default value */
		"sl1280"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, choice.sl2560),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_sl2560_constr_19,  memb_ASN_RRC_sl2560_constraint_4 },
		0, 0, /* No default value */
		"sl2560"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_monitoringSlotPeriodicityAndOffset_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sl1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sl2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sl4 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sl5 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sl8 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* sl10 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* sl16 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* sl20 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* sl40 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* sl80 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* sl160 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* sl320 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* sl640 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* sl1280 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 } /* sl2560 */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_monitoringSlotPeriodicityAndOffset_specs_4 = {
	sizeof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset),
	offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, _asn_ctx),
	offsetof(struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset, present),
	sizeof(((struct ASN_RRC_SearchSpace__monitoringSlotPeriodicityAndOffset *)0)->present),
	asn_MAP_ASN_RRC_monitoringSlotPeriodicityAndOffset_tag2el_4,
	15,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_monitoringSlotPeriodicityAndOffset_4 = {
	"monitoringSlotPeriodicityAndOffset",
	"monitoringSlotPeriodicityAndOffset",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_monitoringSlotPeriodicityAndOffset_constr_4, CHOICE_constraint },
	asn_MBR_ASN_RRC_monitoringSlotPeriodicityAndOffset_4,
	15,	/* Elements count */
	&asn_SPC_ASN_RRC_monitoringSlotPeriodicityAndOffset_specs_4	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel1_value2enum_23[] = {
	{ 0,	2,	"n0" },
	{ 1,	2,	"n1" },
	{ 2,	2,	"n2" },
	{ 3,	2,	"n3" },
	{ 4,	2,	"n4" },
	{ 5,	2,	"n5" },
	{ 6,	2,	"n6" },
	{ 7,	2,	"n8" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel1_enum2value_23[] = {
	0,	/* n0(0) */
	1,	/* n1(1) */
	2,	/* n2(2) */
	3,	/* n3(3) */
	4,	/* n4(4) */
	5,	/* n5(5) */
	6,	/* n6(6) */
	7	/* n8(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel1_specs_23 = {
	asn_MAP_ASN_RRC_aggregationLevel1_value2enum_23,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel1_enum2value_23,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel1_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel1_23 = {
	"aggregationLevel1",
	"aggregationLevel1",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel1_tags_23,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_23)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_23[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel1_tags_23,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_23)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_23[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel1_constr_23, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel1_specs_23	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel2_value2enum_32[] = {
	{ 0,	2,	"n0" },
	{ 1,	2,	"n1" },
	{ 2,	2,	"n2" },
	{ 3,	2,	"n3" },
	{ 4,	2,	"n4" },
	{ 5,	2,	"n5" },
	{ 6,	2,	"n6" },
	{ 7,	2,	"n8" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel2_enum2value_32[] = {
	0,	/* n0(0) */
	1,	/* n1(1) */
	2,	/* n2(2) */
	3,	/* n3(3) */
	4,	/* n4(4) */
	5,	/* n5(5) */
	6,	/* n6(6) */
	7	/* n8(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel2_specs_32 = {
	asn_MAP_ASN_RRC_aggregationLevel2_value2enum_32,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel2_enum2value_32,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel2_tags_32[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel2_32 = {
	"aggregationLevel2",
	"aggregationLevel2",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel2_tags_32,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_32)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_32[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel2_tags_32,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_32)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_32[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel2_constr_32, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel2_specs_32	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel4_value2enum_41[] = {
	{ 0,	2,	"n0" },
	{ 1,	2,	"n1" },
	{ 2,	2,	"n2" },
	{ 3,	2,	"n3" },
	{ 4,	2,	"n4" },
	{ 5,	2,	"n5" },
	{ 6,	2,	"n6" },
	{ 7,	2,	"n8" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel4_enum2value_41[] = {
	0,	/* n0(0) */
	1,	/* n1(1) */
	2,	/* n2(2) */
	3,	/* n3(3) */
	4,	/* n4(4) */
	5,	/* n5(5) */
	6,	/* n6(6) */
	7	/* n8(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel4_specs_41 = {
	asn_MAP_ASN_RRC_aggregationLevel4_value2enum_41,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel4_enum2value_41,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel4_tags_41[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel4_41 = {
	"aggregationLevel4",
	"aggregationLevel4",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel4_tags_41,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_41)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_41[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel4_tags_41,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_41)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_41[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel4_constr_41, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel4_specs_41	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel8_value2enum_50[] = {
	{ 0,	2,	"n0" },
	{ 1,	2,	"n1" },
	{ 2,	2,	"n2" },
	{ 3,	2,	"n3" },
	{ 4,	2,	"n4" },
	{ 5,	2,	"n5" },
	{ 6,	2,	"n6" },
	{ 7,	2,	"n8" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel8_enum2value_50[] = {
	0,	/* n0(0) */
	1,	/* n1(1) */
	2,	/* n2(2) */
	3,	/* n3(3) */
	4,	/* n4(4) */
	5,	/* n5(5) */
	6,	/* n6(6) */
	7	/* n8(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel8_specs_50 = {
	asn_MAP_ASN_RRC_aggregationLevel8_value2enum_50,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel8_enum2value_50,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel8_tags_50[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel8_50 = {
	"aggregationLevel8",
	"aggregationLevel8",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel8_tags_50,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_50)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_50[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel8_tags_50,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_50)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_50[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel8_constr_50, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel8_specs_50	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel16_value2enum_59[] = {
	{ 0,	2,	"n0" },
	{ 1,	2,	"n1" },
	{ 2,	2,	"n2" },
	{ 3,	2,	"n3" },
	{ 4,	2,	"n4" },
	{ 5,	2,	"n5" },
	{ 6,	2,	"n6" },
	{ 7,	2,	"n8" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel16_enum2value_59[] = {
	0,	/* n0(0) */
	1,	/* n1(1) */
	2,	/* n2(2) */
	3,	/* n3(3) */
	4,	/* n4(4) */
	5,	/* n5(5) */
	6,	/* n6(6) */
	7	/* n8(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel16_specs_59 = {
	asn_MAP_ASN_RRC_aggregationLevel16_value2enum_59,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel16_enum2value_59,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel16_tags_59[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel16_59 = {
	"aggregationLevel16",
	"aggregationLevel16",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel16_tags_59,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_59)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_59[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel16_tags_59,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_59)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_59[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel16_constr_59, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel16_specs_59	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_nrofCandidates_22[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__nrofCandidates, aggregationLevel1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel1_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__nrofCandidates, aggregationLevel2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel2_32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__nrofCandidates, aggregationLevel4),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel4_41,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__nrofCandidates, aggregationLevel8),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel8_50,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel8"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__nrofCandidates, aggregationLevel16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel16_59,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel16"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_nrofCandidates_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_nrofCandidates_tag2el_22[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aggregationLevel1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aggregationLevel2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aggregationLevel4 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* aggregationLevel8 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* aggregationLevel16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_nrofCandidates_specs_22 = {
	sizeof(struct ASN_RRC_SearchSpace__nrofCandidates),
	offsetof(struct ASN_RRC_SearchSpace__nrofCandidates, _asn_ctx),
	asn_MAP_ASN_RRC_nrofCandidates_tag2el_22,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_nrofCandidates_22 = {
	"nrofCandidates",
	"nrofCandidates",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_nrofCandidates_tags_22,
	sizeof(asn_DEF_ASN_RRC_nrofCandidates_tags_22)
		/sizeof(asn_DEF_ASN_RRC_nrofCandidates_tags_22[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_nrofCandidates_tags_22,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_nrofCandidates_tags_22)
		/sizeof(asn_DEF_ASN_RRC_nrofCandidates_tags_22[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_nrofCandidates_22,
	5,	/* Elements count */
	&asn_SPC_ASN_RRC_nrofCandidates_specs_22	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_tags_70[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_dci_Format0_0_AndFormat1_0_specs_70 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format0_0_AndFormat1_0),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format0_0_AndFormat1_0, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_70 = {
	"dci-Format0-0-AndFormat1-0",
	"dci-Format0-0-AndFormat1-0",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_tags_70,
	sizeof(asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_tags_70)
		/sizeof(asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_tags_70[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_tags_70,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_tags_70)
		/sizeof(asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_tags_70[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_ASN_RRC_dci_Format0_0_AndFormat1_0_specs_70	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel1_value2enum_74[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel1_enum2value_74[] = {
	0,	/* n1(0) */
	1	/* n2(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel1_specs_74 = {
	asn_MAP_ASN_RRC_aggregationLevel1_value2enum_74,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel1_enum2value_74,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel1_tags_74[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel1_74 = {
	"aggregationLevel1",
	"aggregationLevel1",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel1_tags_74,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_74)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_74[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel1_tags_74,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_74)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel1_tags_74[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel1_constr_74, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel1_specs_74	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel2_value2enum_77[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel2_enum2value_77[] = {
	0,	/* n1(0) */
	1	/* n2(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel2_specs_77 = {
	asn_MAP_ASN_RRC_aggregationLevel2_value2enum_77,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel2_enum2value_77,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel2_tags_77[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel2_77 = {
	"aggregationLevel2",
	"aggregationLevel2",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel2_tags_77,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_77)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_77[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel2_tags_77,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_77)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel2_tags_77[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel2_constr_77, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel2_specs_77	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel4_value2enum_80[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel4_enum2value_80[] = {
	0,	/* n1(0) */
	1	/* n2(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel4_specs_80 = {
	asn_MAP_ASN_RRC_aggregationLevel4_value2enum_80,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel4_enum2value_80,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel4_tags_80[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel4_80 = {
	"aggregationLevel4",
	"aggregationLevel4",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel4_tags_80,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_80)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_80[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel4_tags_80,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_80)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel4_tags_80[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel4_constr_80, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel4_specs_80	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel8_value2enum_83[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel8_enum2value_83[] = {
	0,	/* n1(0) */
	1	/* n2(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel8_specs_83 = {
	asn_MAP_ASN_RRC_aggregationLevel8_value2enum_83,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel8_enum2value_83,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel8_tags_83[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel8_83 = {
	"aggregationLevel8",
	"aggregationLevel8",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel8_tags_83,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_83)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_83[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel8_tags_83,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_83)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel8_tags_83[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel8_constr_83, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel8_specs_83	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_aggregationLevel16_value2enum_86[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" }
};
static const unsigned int asn_MAP_ASN_RRC_aggregationLevel16_enum2value_86[] = {
	0,	/* n1(0) */
	1	/* n2(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_aggregationLevel16_specs_86 = {
	asn_MAP_ASN_RRC_aggregationLevel16_value2enum_86,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_aggregationLevel16_enum2value_86,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_aggregationLevel16_tags_86[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_aggregationLevel16_86 = {
	"aggregationLevel16",
	"aggregationLevel16",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_aggregationLevel16_tags_86,
	sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_86)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_86[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_aggregationLevel16_tags_86,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_86)
		/sizeof(asn_DEF_ASN_RRC_aggregationLevel16_tags_86[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_aggregationLevel16_constr_86, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_aggregationLevel16_specs_86	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_nrofCandidates_SFI_73[] = {
	{ ATF_POINTER, 5, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0__nrofCandidates_SFI, aggregationLevel1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel1_74,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel1"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0__nrofCandidates_SFI, aggregationLevel2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel2_77,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel2"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0__nrofCandidates_SFI, aggregationLevel4),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel4_80,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel4"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0__nrofCandidates_SFI, aggregationLevel8),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel8_83,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel8"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0__nrofCandidates_SFI, aggregationLevel16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_aggregationLevel16_86,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevel16"
		},
};
static const int asn_MAP_ASN_RRC_nrofCandidates_SFI_oms_73[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_nrofCandidates_SFI_tags_73[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_nrofCandidates_SFI_tag2el_73[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aggregationLevel1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aggregationLevel2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aggregationLevel4 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* aggregationLevel8 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* aggregationLevel16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_nrofCandidates_SFI_specs_73 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0__nrofCandidates_SFI),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0__nrofCandidates_SFI, _asn_ctx),
	asn_MAP_ASN_RRC_nrofCandidates_SFI_tag2el_73,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_nrofCandidates_SFI_oms_73,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_nrofCandidates_SFI_73 = {
	"nrofCandidates-SFI",
	"nrofCandidates-SFI",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_nrofCandidates_SFI_tags_73,
	sizeof(asn_DEF_ASN_RRC_nrofCandidates_SFI_tags_73)
		/sizeof(asn_DEF_ASN_RRC_nrofCandidates_SFI_tags_73[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_nrofCandidates_SFI_tags_73,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_nrofCandidates_SFI_tags_73)
		/sizeof(asn_DEF_ASN_RRC_nrofCandidates_SFI_tags_73[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_nrofCandidates_SFI_73,
	5,	/* Elements count */
	&asn_SPC_ASN_RRC_nrofCandidates_SFI_specs_73	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_dci_Format2_0_72[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0, nrofCandidates_SFI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ASN_RRC_nrofCandidates_SFI_73,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nrofCandidates-SFI"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_dci_Format2_0_tags_72[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_dci_Format2_0_tag2el_72[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* nrofCandidates-SFI */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_dci_Format2_0_specs_72 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_0, _asn_ctx),
	asn_MAP_ASN_RRC_dci_Format2_0_tag2el_72,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dci_Format2_0_72 = {
	"dci-Format2-0",
	"dci-Format2-0",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_dci_Format2_0_tags_72,
	sizeof(asn_DEF_ASN_RRC_dci_Format2_0_tags_72)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_0_tags_72[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dci_Format2_0_tags_72,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dci_Format2_0_tags_72)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_0_tags_72[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_dci_Format2_0_72,
	1,	/* Elements count */
	&asn_SPC_ASN_RRC_dci_Format2_0_specs_72	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ASN_RRC_dci_Format2_1_tags_90[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_dci_Format2_1_specs_90 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_1),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_1, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dci_Format2_1_90 = {
	"dci-Format2-1",
	"dci-Format2-1",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_dci_Format2_1_tags_90,
	sizeof(asn_DEF_ASN_RRC_dci_Format2_1_tags_90)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_1_tags_90[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dci_Format2_1_tags_90,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dci_Format2_1_tags_90)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_1_tags_90[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_ASN_RRC_dci_Format2_1_specs_90	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ASN_RRC_dci_Format2_2_tags_92[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_dci_Format2_2_specs_92 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_2),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_2, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dci_Format2_2_92 = {
	"dci-Format2-2",
	"dci-Format2-2",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_dci_Format2_2_tags_92,
	sizeof(asn_DEF_ASN_RRC_dci_Format2_2_tags_92)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_2_tags_92[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dci_Format2_2_tags_92,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dci_Format2_2_tags_92)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_2_tags_92[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_ASN_RRC_dci_Format2_2_specs_92	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_dummy1_value2enum_95[] = {
	{ 0,	3,	"sl1" },
	{ 1,	3,	"sl2" },
	{ 2,	3,	"sl4" },
	{ 3,	3,	"sl5" },
	{ 4,	3,	"sl8" },
	{ 5,	4,	"sl10" },
	{ 6,	4,	"sl16" },
	{ 7,	4,	"sl20" }
};
static const unsigned int asn_MAP_ASN_RRC_dummy1_enum2value_95[] = {
	0,	/* sl1(0) */
	5,	/* sl10(5) */
	6,	/* sl16(6) */
	1,	/* sl2(1) */
	7,	/* sl20(7) */
	2,	/* sl4(2) */
	3,	/* sl5(3) */
	4	/* sl8(4) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_dummy1_specs_95 = {
	asn_MAP_ASN_RRC_dummy1_value2enum_95,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_dummy1_enum2value_95,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_dummy1_tags_95[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dummy1_95 = {
	"dummy1",
	"dummy1",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_dummy1_tags_95,
	sizeof(asn_DEF_ASN_RRC_dummy1_tags_95)
		/sizeof(asn_DEF_ASN_RRC_dummy1_tags_95[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dummy1_tags_95,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dummy1_tags_95)
		/sizeof(asn_DEF_ASN_RRC_dummy1_tags_95[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_dummy1_constr_95, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_dummy1_specs_95	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_dummy2_value2enum_104[] = {
	{ 0,	2,	"n1" },
	{ 1,	2,	"n2" }
};
static const unsigned int asn_MAP_ASN_RRC_dummy2_enum2value_104[] = {
	0,	/* n1(0) */
	1	/* n2(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_dummy2_specs_104 = {
	asn_MAP_ASN_RRC_dummy2_value2enum_104,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_dummy2_enum2value_104,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_dummy2_tags_104[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dummy2_104 = {
	"dummy2",
	"dummy2",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_dummy2_tags_104,
	sizeof(asn_DEF_ASN_RRC_dummy2_tags_104)
		/sizeof(asn_DEF_ASN_RRC_dummy2_tags_104[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dummy2_tags_104,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dummy2_tags_104)
		/sizeof(asn_DEF_ASN_RRC_dummy2_tags_104[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_dummy2_constr_104, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_dummy2_specs_104	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_dci_Format2_3_94[] = {
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_3, dummy1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_dummy1_95,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dummy1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_3, dummy2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_dummy2_104,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dummy2"
		},
};
static const int asn_MAP_ASN_RRC_dci_Format2_3_oms_94[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_dci_Format2_3_tags_94[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_dci_Format2_3_tag2el_94[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dummy1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* dummy2 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_dci_Format2_3_specs_94 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_3),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common__dci_Format2_3, _asn_ctx),
	asn_MAP_ASN_RRC_dci_Format2_3_tag2el_94,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_dci_Format2_3_oms_94,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dci_Format2_3_94 = {
	"dci-Format2-3",
	"dci-Format2-3",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_dci_Format2_3_tags_94,
	sizeof(asn_DEF_ASN_RRC_dci_Format2_3_tags_94)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_3_tags_94[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dci_Format2_3_tags_94,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dci_Format2_3_tags_94)
		/sizeof(asn_DEF_ASN_RRC_dci_Format2_3_tags_94[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_dci_Format2_3_94,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_dci_Format2_3_specs_94	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_common_69[] = {
	{ ATF_POINTER, 5, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common, dci_Format0_0_AndFormat1_0),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ASN_RRC_dci_Format0_0_AndFormat1_0_70,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dci-Format0-0-AndFormat1-0"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common, dci_Format2_0),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ASN_RRC_dci_Format2_0_72,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dci-Format2-0"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common, dci_Format2_1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ASN_RRC_dci_Format2_1_90,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dci-Format2-1"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common, dci_Format2_2),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ASN_RRC_dci_Format2_2_92,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dci-Format2-2"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common, dci_Format2_3),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ASN_RRC_dci_Format2_3_94,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dci-Format2-3"
		},
};
static const int asn_MAP_ASN_RRC_common_oms_69[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_common_tags_69[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_common_tag2el_69[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dci-Format0-0-AndFormat1-0 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dci-Format2-0 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dci-Format2-1 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dci-Format2-2 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* dci-Format2-3 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_common_specs_69 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__common),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__common, _asn_ctx),
	asn_MAP_ASN_RRC_common_tag2el_69,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_common_oms_69,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_common_69 = {
	"common",
	"common",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_common_tags_69,
	sizeof(asn_DEF_ASN_RRC_common_tags_69)
		/sizeof(asn_DEF_ASN_RRC_common_tags_69[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_common_tags_69,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_common_tags_69)
		/sizeof(asn_DEF_ASN_RRC_common_tags_69[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_common_69,
	5,	/* Elements count */
	&asn_SPC_ASN_RRC_common_specs_69	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_dci_Formats_value2enum_109[] = {
	{ 0,	18,	"formats0-0-And-1-0" },
	{ 1,	18,	"formats0-1-And-1-1" }
};
static const unsigned int asn_MAP_ASN_RRC_dci_Formats_enum2value_109[] = {
	0,	/* formats0-0-And-1-0(0) */
	1	/* formats0-1-And-1-1(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_dci_Formats_specs_109 = {
	asn_MAP_ASN_RRC_dci_Formats_value2enum_109,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_dci_Formats_enum2value_109,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_dci_Formats_tags_109[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_dci_Formats_109 = {
	"dci-Formats",
	"dci-Formats",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_dci_Formats_tags_109,
	sizeof(asn_DEF_ASN_RRC_dci_Formats_tags_109)
		/sizeof(asn_DEF_ASN_RRC_dci_Formats_tags_109[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_dci_Formats_tags_109,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_dci_Formats_tags_109)
		/sizeof(asn_DEF_ASN_RRC_dci_Formats_tags_109[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_dci_Formats_constr_109, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_dci_Formats_specs_109	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_ue_Specific_108[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__ue_Specific, dci_Formats),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_dci_Formats_109,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dci-Formats"
		},
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_ue_Specific_tags_108[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_ue_Specific_tag2el_108[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* dci-Formats */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_ue_Specific_specs_108 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType__ue_Specific),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType__ue_Specific, _asn_ctx),
	asn_MAP_ASN_RRC_ue_Specific_tag2el_108,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ue_Specific_108 = {
	"ue-Specific",
	"ue-Specific",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_ue_Specific_tags_108,
	sizeof(asn_DEF_ASN_RRC_ue_Specific_tags_108)
		/sizeof(asn_DEF_ASN_RRC_ue_Specific_tags_108[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_ue_Specific_tags_108,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_ue_Specific_tags_108)
		/sizeof(asn_DEF_ASN_RRC_ue_Specific_tags_108[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_ue_Specific_108,
	1,	/* Elements count */
	&asn_SPC_ASN_RRC_ue_Specific_specs_108	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_searchSpaceType_68[] = {
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType, choice.common),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ASN_RRC_common_69,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"common"
		},
	{ ATF_POINTER, 0, offsetof(struct ASN_RRC_SearchSpace__searchSpaceType, choice.ue_Specific),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ASN_RRC_ue_Specific_108,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ue-Specific"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_searchSpaceType_tag2el_68[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* common */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ue-Specific */
};
static asn_CHOICE_specifics_t asn_SPC_ASN_RRC_searchSpaceType_specs_68 = {
	sizeof(struct ASN_RRC_SearchSpace__searchSpaceType),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType, _asn_ctx),
	offsetof(struct ASN_RRC_SearchSpace__searchSpaceType, present),
	sizeof(((struct ASN_RRC_SearchSpace__searchSpaceType *)0)->present),
	asn_MAP_ASN_RRC_searchSpaceType_tag2el_68,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_searchSpaceType_68 = {
	"searchSpaceType",
	"searchSpaceType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ASN_RRC_searchSpaceType_constr_68, CHOICE_constraint },
	asn_MBR_ASN_RRC_searchSpaceType_68,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_searchSpaceType_specs_68	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_SearchSpace_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASN_RRC_SearchSpace, searchSpaceId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_SearchSpaceId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"searchSpaceId"
		},
	{ ATF_POINTER, 6, offsetof(struct ASN_RRC_SearchSpace, controlResourceSetId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_ControlResourceSetId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"controlResourceSetId"
		},
	{ ATF_POINTER, 5, offsetof(struct ASN_RRC_SearchSpace, monitoringSlotPeriodicityAndOffset),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_monitoringSlotPeriodicityAndOffset_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"monitoringSlotPeriodicityAndOffset"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_SearchSpace, duration),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_duration_constr_20,  memb_ASN_RRC_duration_constraint_1 },
		0, 0, /* No default value */
		"duration"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_SearchSpace, monitoringSymbolsWithinSlot),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_ASN_RRC_monitoringSymbolsWithinSlot_constr_21,  memb_ASN_RRC_monitoringSymbolsWithinSlot_constraint_1 },
		0, 0, /* No default value */
		"monitoringSymbolsWithinSlot"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_SearchSpace, nrofCandidates),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_ASN_RRC_nrofCandidates_22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nrofCandidates"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_SearchSpace, searchSpaceType),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASN_RRC_searchSpaceType_68,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"searchSpaceType"
		},
};
static const int asn_MAP_ASN_RRC_SearchSpace_oms_1[] = { 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_SearchSpace_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_SearchSpace_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* searchSpaceId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* controlResourceSetId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* monitoringSlotPeriodicityAndOffset */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* duration */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* monitoringSymbolsWithinSlot */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* nrofCandidates */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* searchSpaceType */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SearchSpace_specs_1 = {
	sizeof(struct ASN_RRC_SearchSpace),
	offsetof(struct ASN_RRC_SearchSpace, _asn_ctx),
	asn_MAP_ASN_RRC_SearchSpace_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_SearchSpace_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SearchSpace = {
	"SearchSpace",
	"SearchSpace",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_SearchSpace_tags_1,
	sizeof(asn_DEF_ASN_RRC_SearchSpace_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SearchSpace_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_SearchSpace_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_SearchSpace_tags_1)
		/sizeof(asn_DEF_ASN_RRC_SearchSpace_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_SearchSpace_1,
	7,	/* Elements count */
	&asn_SPC_ASN_RRC_SearchSpace_specs_1	/* Additional specs */
};

