/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_IMS_ParametersCommon_H_
#define	_ASN_RRC_IMS_ParametersCommon_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_IMS_ParametersCommon__voiceOverEUTRA_5GC {
	ASN_RRC_IMS_ParametersCommon__voiceOverEUTRA_5GC_supported	= 0
} e_ASN_RRC_IMS_ParametersCommon__voiceOverEUTRA_5GC;
typedef enum ASN_RRC_IMS_ParametersCommon__ext1__voiceOverSCG_BearerEUTRA_5GC {
	ASN_RRC_IMS_ParametersCommon__ext1__voiceOverSCG_BearerEUTRA_5GC_supported	= 0
} e_ASN_RRC_IMS_ParametersCommon__ext1__voiceOverSCG_BearerEUTRA_5GC;

/* ASN_RRC_IMS-ParametersCommon */
typedef struct ASN_RRC_IMS_ParametersCommon {
	long	*voiceOverEUTRA_5GC;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct ASN_RRC_IMS_ParametersCommon__ext1 {
		long	*voiceOverSCG_BearerEUTRA_5GC;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_IMS_ParametersCommon_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_voiceOverEUTRA_5GC_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_voiceOverSCG_BearerEUTRA_5GC_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_IMS_ParametersCommon;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_IMS_ParametersCommon_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_IMS_ParametersCommon_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_IMS_ParametersCommon_H_ */
#include <asn_internal.h>
