/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_DummyA_H_
#define	_ASN_RRC_DummyA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC {
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p2	= 0,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p4	= 1,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p8	= 2,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p12	= 3,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p16	= 4,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p24	= 5,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p32	= 6,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p40	= 7,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p48	= 8,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p56	= 9,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p64	= 10,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p72	= 11,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p80	= 12,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p88	= 13,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p96	= 14,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p104	= 15,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p112	= 16,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p120	= 17,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p128	= 18,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p136	= 19,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p144	= 20,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p152	= 21,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p160	= 22,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p168	= 23,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p176	= 24,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p184	= 25,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p192	= 26,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p200	= 27,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p208	= 28,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p216	= 29,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p224	= 30,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p232	= 31,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p240	= 32,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p248	= 33,
	ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC_p256	= 34
} e_ASN_RRC_DummyA__maxNumberPortsAcrossNZP_CSI_RS_PerCC;
typedef enum ASN_RRC_DummyA__maxNumberCS_IM_PerCC {
	ASN_RRC_DummyA__maxNumberCS_IM_PerCC_n1	= 0,
	ASN_RRC_DummyA__maxNumberCS_IM_PerCC_n2	= 1,
	ASN_RRC_DummyA__maxNumberCS_IM_PerCC_n4	= 2,
	ASN_RRC_DummyA__maxNumberCS_IM_PerCC_n8	= 3,
	ASN_RRC_DummyA__maxNumberCS_IM_PerCC_n16	= 4,
	ASN_RRC_DummyA__maxNumberCS_IM_PerCC_n32	= 5
} e_ASN_RRC_DummyA__maxNumberCS_IM_PerCC;
typedef enum ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC {
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n5	= 0,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n6	= 1,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n7	= 2,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n8	= 3,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n9	= 4,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n10	= 5,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n12	= 6,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n14	= 7,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n16	= 8,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n18	= 9,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n20	= 10,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n22	= 11,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n24	= 12,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n26	= 13,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n28	= 14,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n30	= 15,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n32	= 16,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n34	= 17,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n36	= 18,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n38	= 19,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n40	= 20,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n42	= 21,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n44	= 22,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n46	= 23,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n48	= 24,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n50	= 25,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n52	= 26,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n54	= 27,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n56	= 28,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n58	= 29,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n60	= 30,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n62	= 31,
	ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC_n64	= 32
} e_ASN_RRC_DummyA__maxNumberSimultaneousCSI_RS_ActBWP_AllCC;
typedef enum ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC {
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p8	= 0,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p12	= 1,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p16	= 2,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p24	= 3,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p32	= 4,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p40	= 5,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p48	= 6,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p56	= 7,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p64	= 8,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p72	= 9,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p80	= 10,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p88	= 11,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p96	= 12,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p104	= 13,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p112	= 14,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p120	= 15,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p128	= 16,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p136	= 17,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p144	= 18,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p152	= 19,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p160	= 20,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p168	= 21,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p176	= 22,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p184	= 23,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p192	= 24,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p200	= 25,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p208	= 26,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p216	= 27,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p224	= 28,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p232	= 29,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p240	= 30,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p248	= 31,
	ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_p256	= 32
} e_ASN_RRC_DummyA__totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC;

/* ASN_RRC_DummyA */
typedef struct ASN_RRC_DummyA {
	long	 maxNumberNZP_CSI_RS_PerCC;
	long	 maxNumberPortsAcrossNZP_CSI_RS_PerCC;
	long	 maxNumberCS_IM_PerCC;
	long	 maxNumberSimultaneousCSI_RS_ActBWP_AllCC;
	long	 totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_DummyA_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberPortsAcrossNZP_CSI_RS_PerCC_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberCS_IM_PerCC_39;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_maxNumberSimultaneousCSI_RS_ActBWP_AllCC_46;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_totalNumberPortsSimultaneousCSI_RS_ActBWP_AllCC_80;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_DummyA;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_DummyA_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_DummyA_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_DummyA_H_ */
#include <asn_internal.h>
