/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_PUCCH_PathlossReferenceRS_H_
#define	_ASN_RRC_PUCCH_PathlossReferenceRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_RRC_PUCCH-PathlossReferenceRS-Id.h"
#include "ASN_RRC_SSB-Index.h"
#include "ASN_RRC_NZP-CSI-RS-ResourceId.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_PUCCH_PathlossReferenceRS__referenceSignal_PR {
	ASN_RRC_PUCCH_PathlossReferenceRS__referenceSignal_PR_NOTHING,	/* No components present */
	ASN_RRC_PUCCH_PathlossReferenceRS__referenceSignal_PR_ssb_Index,
	ASN_RRC_PUCCH_PathlossReferenceRS__referenceSignal_PR_csi_RS_Index
} ASN_RRC_PUCCH_PathlossReferenceRS__referenceSignal_PR;

/* ASN_RRC_PUCCH-PathlossReferenceRS */
typedef struct ASN_RRC_PUCCH_PathlossReferenceRS {
	ASN_RRC_PUCCH_PathlossReferenceRS_Id_t	 pucch_PathlossReferenceRS_Id;
	struct ASN_RRC_PUCCH_PathlossReferenceRS__referenceSignal {
		ASN_RRC_PUCCH_PathlossReferenceRS__referenceSignal_PR present;
		union ASN_RRC_PUCCH_PathlossReferenceRS__ASN_RRC_referenceSignal_u {
			ASN_RRC_SSB_Index_t	 ssb_Index;
			ASN_RRC_NZP_CSI_RS_ResourceId_t	 csi_RS_Index;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} referenceSignal;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_PUCCH_PathlossReferenceRS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_PUCCH_PathlossReferenceRS;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_PUCCH_PathlossReferenceRS_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_PUCCH_PathlossReferenceRS_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_PUCCH_PathlossReferenceRS_H_ */
#include <asn_internal.h>
