/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_SRS_PeriodicityAndOffset_H_
#define	_ASN_RRC_SRS_PeriodicityAndOffset_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SRS_PeriodicityAndOffset_PR {
	ASN_RRC_SRS_PeriodicityAndOffset_PR_NOTHING,	/* No components present */
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl1,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl2,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl4,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl5,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl8,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl10,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl16,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl20,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl32,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl40,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl64,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl80,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl160,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl320,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl640,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl1280,
	ASN_RRC_SRS_PeriodicityAndOffset_PR_sl2560
} ASN_RRC_SRS_PeriodicityAndOffset_PR;

/* ASN_RRC_SRS-PeriodicityAndOffset */
typedef struct ASN_RRC_SRS_PeriodicityAndOffset {
	ASN_RRC_SRS_PeriodicityAndOffset_PR present;
	union ASN_RRC_SRS_PeriodicityAndOffset_u {
		NULL_t	 sl1;
		long	 sl2;
		long	 sl4;
		long	 sl5;
		long	 sl8;
		long	 sl10;
		long	 sl16;
		long	 sl20;
		long	 sl32;
		long	 sl40;
		long	 sl64;
		long	 sl80;
		long	 sl160;
		long	 sl320;
		long	 sl640;
		long	 sl1280;
		long	 sl2560;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SRS_PeriodicityAndOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SRS_PeriodicityAndOffset;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_SRS_PeriodicityAndOffset_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SRS_PeriodicityAndOffset_1[17];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_SRS_PeriodicityAndOffset_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SRS_PeriodicityAndOffset_H_ */
#include <asn_internal.h>
