/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#include "ASN_RRC_RF-ParametersMRDC.h"

#include "ASN_RRC_BandCombinationList.h"
#include "ASN_RRC_FreqBandList.h"
#include "ASN_RRC_BandCombinationList-v1540.h"
#include "ASN_RRC_BandCombinationList-v1550.h"
#include "ASN_RRC_BandCombinationList-v1560.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_ASN_RRC_srs_SwitchingTimeRequested_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_value2enum_6[] = {
	{ 0,	4,	"true" }
};
static const unsigned int asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_enum2value_6[] = {
	0	/* true(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ASN_RRC_srs_SwitchingTimeRequested_specs_6 = {
	asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_ASN_RRC_srs_SwitchingTimeRequested_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_6 = {
	"srs-SwitchingTimeRequested",
	"srs-SwitchingTimeRequested",
	&asn_OP_NativeEnumerated,
	asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_6,
	sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_6)
		/sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_6[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_6,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_6)
		/sizeof(asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_tags_6[0]), /* 2 */
	{ 0, &asn_PER_type_ASN_RRC_srs_SwitchingTimeRequested_constr_6, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ASN_RRC_srs_SwitchingTimeRequested_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_ext1_5[] = {
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_RF_ParametersMRDC__ext1, srs_SwitchingTimeRequested),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_srs_SwitchingTimeRequested_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"srs-SwitchingTimeRequested"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_RF_ParametersMRDC__ext1, supportedBandCombinationList_v1540),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1540,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1540"
		},
};
static const int asn_MAP_ASN_RRC_ext1_oms_5[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_ext1_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_ext1_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* srs-SwitchingTimeRequested */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* supportedBandCombinationList-v1540 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_ext1_specs_5 = {
	sizeof(struct ASN_RRC_RF_ParametersMRDC__ext1),
	offsetof(struct ASN_RRC_RF_ParametersMRDC__ext1, _asn_ctx),
	asn_MAP_ASN_RRC_ext1_tag2el_5,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_ext1_oms_5,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ext1_5 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_ext1_tags_5,
	sizeof(asn_DEF_ASN_RRC_ext1_tags_5)
		/sizeof(asn_DEF_ASN_RRC_ext1_tags_5[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_ext1_tags_5,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_ext1_tags_5)
		/sizeof(asn_DEF_ASN_RRC_ext1_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_ext1_5,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_ext1_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_ext2_9[] = {
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_RF_ParametersMRDC__ext2, supportedBandCombinationList_v1550),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1550,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1550"
		},
};
static const int asn_MAP_ASN_RRC_ext2_oms_9[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_ext2_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_ext2_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* supportedBandCombinationList-v1550 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_ext2_specs_9 = {
	sizeof(struct ASN_RRC_RF_ParametersMRDC__ext2),
	offsetof(struct ASN_RRC_RF_ParametersMRDC__ext2, _asn_ctx),
	asn_MAP_ASN_RRC_ext2_tag2el_9,
	1,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_ext2_oms_9,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ext2_9 = {
	"ext2",
	"ext2",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_ext2_tags_9,
	sizeof(asn_DEF_ASN_RRC_ext2_tags_9)
		/sizeof(asn_DEF_ASN_RRC_ext2_tags_9[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_ext2_tags_9,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_ext2_tags_9)
		/sizeof(asn_DEF_ASN_RRC_ext2_tags_9[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_ext2_9,
	1,	/* Elements count */
	&asn_SPC_ASN_RRC_ext2_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ASN_RRC_ext3_11[] = {
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_RF_ParametersMRDC__ext3, supportedBandCombinationList_v1560),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList_v1560,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList-v1560"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_RF_ParametersMRDC__ext3, supportedBandCombinationListNEDC_Only),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationListNEDC-Only"
		},
};
static const int asn_MAP_ASN_RRC_ext3_oms_11[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_ext3_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_ext3_tag2el_11[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedBandCombinationList-v1560 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* supportedBandCombinationListNEDC-Only */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_ext3_specs_11 = {
	sizeof(struct ASN_RRC_RF_ParametersMRDC__ext3),
	offsetof(struct ASN_RRC_RF_ParametersMRDC__ext3, _asn_ctx),
	asn_MAP_ASN_RRC_ext3_tag2el_11,
	2,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_ext3_oms_11,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ext3_11 = {
	"ext3",
	"ext3",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_ext3_tags_11,
	sizeof(asn_DEF_ASN_RRC_ext3_tags_11)
		/sizeof(asn_DEF_ASN_RRC_ext3_tags_11[0]) - 1, /* 1 */
	asn_DEF_ASN_RRC_ext3_tags_11,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_ext3_tags_11)
		/sizeof(asn_DEF_ASN_RRC_ext3_tags_11[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_ext3_11,
	2,	/* Elements count */
	&asn_SPC_ASN_RRC_ext3_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ASN_RRC_RF_ParametersMRDC_1[] = {
	{ ATF_POINTER, 5, offsetof(struct ASN_RRC_RF_ParametersMRDC, supportedBandCombinationList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_BandCombinationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandCombinationList"
		},
	{ ATF_POINTER, 4, offsetof(struct ASN_RRC_RF_ParametersMRDC, appliedFreqBandListFilter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ASN_RRC_FreqBandList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"appliedFreqBandListFilter"
		},
	{ ATF_POINTER, 3, offsetof(struct ASN_RRC_RF_ParametersMRDC, ext1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ASN_RRC_ext1_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext1"
		},
	{ ATF_POINTER, 2, offsetof(struct ASN_RRC_RF_ParametersMRDC, ext2),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ASN_RRC_ext2_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext2"
		},
	{ ATF_POINTER, 1, offsetof(struct ASN_RRC_RF_ParametersMRDC, ext3),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ASN_RRC_ext3_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ext3"
		},
};
static const int asn_MAP_ASN_RRC_RF_ParametersMRDC_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ASN_RRC_RF_ParametersMRDC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedBandCombinationList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* appliedFreqBandListFilter */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ext1 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ext2 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ext3 */
};
asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_RF_ParametersMRDC_specs_1 = {
	sizeof(struct ASN_RRC_RF_ParametersMRDC),
	offsetof(struct ASN_RRC_RF_ParametersMRDC, _asn_ctx),
	asn_MAP_ASN_RRC_RF_ParametersMRDC_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ASN_RRC_RF_ParametersMRDC_oms_1,	/* Optional members */
	2, 3,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ASN_RRC_RF_ParametersMRDC = {
	"RF-ParametersMRDC",
	"RF-ParametersMRDC",
	&asn_OP_SEQUENCE,
	asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1,
	sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1)
		/sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1[0]), /* 1 */
	asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1)
		/sizeof(asn_DEF_ASN_RRC_RF_ParametersMRDC_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ASN_RRC_RF_ParametersMRDC_1,
	5,	/* Elements count */
	&asn_SPC_ASN_RRC_RF_ParametersMRDC_specs_1	/* Additional specs */
};

