/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_FeatureSetUplink_v1540_H_
#define	_ASN_RRC_FeatureSetUplink_v1540_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_FeatureSetUplink_v1540__zeroSlotOffsetAperiodicSRS {
	ASN_RRC_FeatureSetUplink_v1540__zeroSlotOffsetAperiodicSRS_supported	= 0
} e_ASN_RRC_FeatureSetUplink_v1540__zeroSlotOffsetAperiodicSRS;
typedef enum ASN_RRC_FeatureSetUplink_v1540__pa_PhaseDiscontinuityImpacts {
	ASN_RRC_FeatureSetUplink_v1540__pa_PhaseDiscontinuityImpacts_supported	= 0
} e_ASN_RRC_FeatureSetUplink_v1540__pa_PhaseDiscontinuityImpacts;
typedef enum ASN_RRC_FeatureSetUplink_v1540__pusch_SeparationWithGap {
	ASN_RRC_FeatureSetUplink_v1540__pusch_SeparationWithGap_supported	= 0
} e_ASN_RRC_FeatureSetUplink_v1540__pusch_SeparationWithGap;
typedef enum ASN_RRC_FeatureSetUplink_v1540__ul_MCS_TableAlt_DynamicIndication {
	ASN_RRC_FeatureSetUplink_v1540__ul_MCS_TableAlt_DynamicIndication_supported	= 0
} e_ASN_RRC_FeatureSetUplink_v1540__ul_MCS_TableAlt_DynamicIndication;

/* Forward declarations */
struct ASN_RRC_ProcessingParameters;

/* ASN_RRC_FeatureSetUplink-v1540 */
typedef struct ASN_RRC_FeatureSetUplink_v1540 {
	long	*zeroSlotOffsetAperiodicSRS;	/* OPTIONAL */
	long	*pa_PhaseDiscontinuityImpacts;	/* OPTIONAL */
	long	*pusch_SeparationWithGap;	/* OPTIONAL */
	struct ASN_RRC_FeatureSetUplink_v1540__pusch_ProcessingType2 {
		struct ASN_RRC_ProcessingParameters	*scs_15kHz;	/* OPTIONAL */
		struct ASN_RRC_ProcessingParameters	*scs_30kHz;	/* OPTIONAL */
		struct ASN_RRC_ProcessingParameters	*scs_60kHz;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pusch_ProcessingType2;
	long	*ul_MCS_TableAlt_DynamicIndication;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_FeatureSetUplink_v1540_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_zeroSlotOffsetAperiodicSRS_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_pa_PhaseDiscontinuityImpacts_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_pusch_SeparationWithGap_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ul_MCS_TableAlt_DynamicIndication_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_FeatureSetUplink_v1540;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_FeatureSetUplink_v1540_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_FeatureSetUplink_v1540_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_FeatureSetUplink_v1540_H_ */
#include <asn_internal.h>
