/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_ControlResourceSet_H_
#define	_ASN_RRC_ControlResourceSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_RRC_ControlResourceSetId.h"
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>
#include "ASN_RRC_TCI-StateId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_ControlResourceSet__cce_REG_MappingType_PR {
	ASN_RRC_ControlResourceSet__cce_REG_MappingType_PR_NOTHING,	/* No components present */
	ASN_RRC_ControlResourceSet__cce_REG_MappingType_PR_interleaved,
	ASN_RRC_ControlResourceSet__cce_REG_MappingType_PR_nonInterleaved
} ASN_RRC_ControlResourceSet__cce_REG_MappingType_PR;
typedef enum ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__reg_BundleSize {
	ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__reg_BundleSize_n2	= 0,
	ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__reg_BundleSize_n3	= 1,
	ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__reg_BundleSize_n6	= 2
} e_ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__reg_BundleSize;
typedef enum ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__interleaverSize {
	ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__interleaverSize_n2	= 0,
	ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__interleaverSize_n3	= 1,
	ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__interleaverSize_n6	= 2
} e_ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved__interleaverSize;
typedef enum ASN_RRC_ControlResourceSet__precoderGranularity {
	ASN_RRC_ControlResourceSet__precoderGranularity_sameAsREG_bundle	= 0,
	ASN_RRC_ControlResourceSet__precoderGranularity_allContiguousRBs	= 1
} e_ASN_RRC_ControlResourceSet__precoderGranularity;
typedef enum ASN_RRC_ControlResourceSet__tci_PresentInDCI {
	ASN_RRC_ControlResourceSet__tci_PresentInDCI_enabled	= 0
} e_ASN_RRC_ControlResourceSet__tci_PresentInDCI;

/* ASN_RRC_ControlResourceSet */
typedef struct ASN_RRC_ControlResourceSet {
	ASN_RRC_ControlResourceSetId_t	 controlResourceSetId;
	BIT_STRING_t	 frequencyDomainResources;
	long	 duration;
	struct ASN_RRC_ControlResourceSet__cce_REG_MappingType {
		ASN_RRC_ControlResourceSet__cce_REG_MappingType_PR present;
		union ASN_RRC_ControlResourceSet__ASN_RRC_cce_REG_MappingType_u {
			struct ASN_RRC_ControlResourceSet__cce_REG_MappingType__interleaved {
				long	 reg_BundleSize;
				long	 interleaverSize;
				long	*shiftIndex;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *interleaved;
			NULL_t	 nonInterleaved;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} cce_REG_MappingType;
	long	 precoderGranularity;
	struct ASN_RRC_ControlResourceSet__tci_StatesPDCCH_ToAddList {
		A_SEQUENCE_OF(ASN_RRC_TCI_StateId_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tci_StatesPDCCH_ToAddList;
	struct ASN_RRC_ControlResourceSet__tci_StatesPDCCH_ToReleaseList {
		A_SEQUENCE_OF(ASN_RRC_TCI_StateId_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tci_StatesPDCCH_ToReleaseList;
	long	*tci_PresentInDCI;	/* OPTIONAL */
	long	*pdcch_DMRS_ScramblingID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_ControlResourceSet_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_reg_BundleSize_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_interleaverSize_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_precoderGranularity_17;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_tci_PresentInDCI_24;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_ControlResourceSet;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_ControlResourceSet_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_ControlResourceSet_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_ControlResourceSet_H_ */
#include <asn_internal.h>
