/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_SystemInformation_IEs_H_
#define	_ASN_RRC_SystemInformation_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR {
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_NOTHING,	/* No components present */
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib2,
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib3,
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib4,
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib5,
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib6,
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib7,
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib8,
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR_sib9
	/* Extensions may appear below */
	
} ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR;

/* Forward declarations */
struct ASN_RRC_SIB2;
struct ASN_RRC_SIB3;
struct ASN_RRC_SIB4;
struct ASN_RRC_SIB5;
struct ASN_RRC_SIB6;
struct ASN_RRC_SIB7;
struct ASN_RRC_SIB8;
struct ASN_RRC_SIB9;

/* Forward definitions */
typedef struct ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member {
	ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo__Member_PR present;
	union ASN_RRC_SystemInformation_IEs__ASN_RRC_sib_TypeAndInfo__ASN_RRC_Member_u {
		struct ASN_RRC_SIB2	*sib2;
		struct ASN_RRC_SIB3	*sib3;
		struct ASN_RRC_SIB4	*sib4;
		struct ASN_RRC_SIB5	*sib5;
		struct ASN_RRC_SIB6	*sib6;
		struct ASN_RRC_SIB7	*sib7;
		struct ASN_RRC_SIB8	*sib8;
		struct ASN_RRC_SIB9	*sib9;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformation_IEs__sib_TypeAndInfo__Member;

/* ASN_RRC_SystemInformation-IEs */
typedef struct ASN_RRC_SystemInformation_IEs {
	struct ASN_RRC_SystemInformation_IEs__sib_TypeAndInfo {
		A_SEQUENCE_OF(SystemInformation_IEs__sib_TypeAndInfo__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sib_TypeAndInfo;
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct ASN_RRC_SystemInformation_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_SystemInformation_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_SystemInformation_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ASN_RRC_SystemInformation_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_SystemInformation_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_SystemInformation_IEs_H_ */
#include <asn_internal.h>
