/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_ASN_RRC_BandParameters_H_
#define	_ASN_RRC_BandParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_RRC_FreqBandIndicatorEUTRA.h"
#include "ASN_RRC_CA-BandwidthClassEUTRA.h"
#include <constr_SEQUENCE.h>
#include "ASN_RRC_FreqBandIndicatorNR.h"
#include "ASN_RRC_CA-BandwidthClassNR.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_RRC_BandParameters_PR {
	ASN_RRC_BandParameters_PR_NOTHING,	/* No components present */
	ASN_RRC_BandParameters_PR_eutra,
	ASN_RRC_BandParameters_PR_nr
} ASN_RRC_BandParameters_PR;

/* ASN_RRC_BandParameters */
typedef struct ASN_RRC_BandParameters {
	ASN_RRC_BandParameters_PR present;
	union ASN_RRC_BandParameters_u {
		struct ASN_RRC_BandParameters__eutra {
			ASN_RRC_FreqBandIndicatorEUTRA_t	 bandEUTRA;
			ASN_RRC_CA_BandwidthClassEUTRA_t	*ca_BandwidthClassDL_EUTRA;	/* OPTIONAL */
			ASN_RRC_CA_BandwidthClassEUTRA_t	*ca_BandwidthClassUL_EUTRA;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *eutra;
		struct ASN_RRC_BandParameters__nr {
			ASN_RRC_FreqBandIndicatorNR_t	 bandNR;
			ASN_RRC_CA_BandwidthClassNR_t	*ca_BandwidthClassDL_NR;	/* OPTIONAL */
			ASN_RRC_CA_BandwidthClassNR_t	*ca_BandwidthClassUL_NR;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_RRC_BandParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_RRC_BandParameters;
extern asn_CHOICE_specifics_t asn_SPC_ASN_RRC_BandParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_RRC_BandParameters_1[2];
extern asn_per_constraints_t asn_PER_type_ASN_RRC_BandParameters_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_RRC_BandParameters_H_ */
#include <asn_internal.h>
