/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_RRCReconfiguration_H_
#define	_RRC_RRCReconfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC_RRC-TransactionIdentifier.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_RRCReconfiguration__criticalExtensions_PR {
	RRC_RRCReconfiguration__criticalExtensions_PR_NOTHING,	/* No components present */
	RRC_RRCReconfiguration__criticalExtensions_PR_rrcReconfiguration,
	RRC_RRCReconfiguration__criticalExtensions_PR_criticalExtensionsFuture
} RRC_RRCReconfiguration__criticalExtensions_PR;

/* Forward declarations */
struct RRC_RRCReconfiguration_IEs;

/* RRC_RRCReconfiguration */
typedef struct RRC_RRCReconfiguration {
	RRC_RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct RRC_RRCReconfiguration__criticalExtensions {
		RRC_RRCReconfiguration__criticalExtensions_PR present;
		union RRC_RRCReconfiguration__RRC_criticalExtensions_u {
			struct RRC_RRCReconfiguration_IEs	*rrcReconfiguration;
			struct RRC_RRCReconfiguration__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_RRCReconfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRC_RRCReconfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_RRCReconfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_RRCReconfiguration_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_RRCReconfiguration_H_ */
#include <asn_internal.h>
