/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_EventTriggerConfig_H_
#define	_RRC_EventTriggerConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC_NR-RS-Type.h"
#include "RRC_ReportInterval.h"
#include <NativeEnumerated.h>
#include "RRC_MeasReportQuantity.h"
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include "RRC_MeasTriggerQuantity.h"
#include "RRC_Hysteresis.h"
#include "RRC_TimeToTrigger.h"
#include <constr_SEQUENCE.h>
#include "RRC_MeasTriggerQuantityOffset.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_EventTriggerConfig__eventId_PR {
	RRC_EventTriggerConfig__eventId_PR_NOTHING,	/* No components present */
	RRC_EventTriggerConfig__eventId_PR_eventA1,
	RRC_EventTriggerConfig__eventId_PR_eventA2,
	RRC_EventTriggerConfig__eventId_PR_eventA3,
	RRC_EventTriggerConfig__eventId_PR_eventA4,
	RRC_EventTriggerConfig__eventId_PR_eventA5,
	RRC_EventTriggerConfig__eventId_PR_eventA6
	/* Extensions may appear below */
	
} RRC_EventTriggerConfig__eventId_PR;
typedef enum RRC_EventTriggerConfig__reportAmount {
	RRC_EventTriggerConfig__reportAmount_r1	= 0,
	RRC_EventTriggerConfig__reportAmount_r2	= 1,
	RRC_EventTriggerConfig__reportAmount_r4	= 2,
	RRC_EventTriggerConfig__reportAmount_r8	= 3,
	RRC_EventTriggerConfig__reportAmount_r16	= 4,
	RRC_EventTriggerConfig__reportAmount_r32	= 5,
	RRC_EventTriggerConfig__reportAmount_r64	= 6,
	RRC_EventTriggerConfig__reportAmount_infinity	= 7
} e_RRC_EventTriggerConfig__reportAmount;
typedef enum RRC_EventTriggerConfig__reportAddNeighMeas {
	RRC_EventTriggerConfig__reportAddNeighMeas_setup	= 0
} e_RRC_EventTriggerConfig__reportAddNeighMeas;

/* Forward declarations */
struct RRC_MeasReportQuantity;

/* RRC_EventTriggerConfig */
typedef struct RRC_EventTriggerConfig {
	struct RRC_EventTriggerConfig__eventId {
		RRC_EventTriggerConfig__eventId_PR present;
		union RRC_EventTriggerConfig__RRC_eventId_u {
			struct RRC_EventTriggerConfig__eventId__eventA1 {
				RRC_MeasTriggerQuantity_t	 a1_Threshold;
				BOOLEAN_t	 reportOnLeave;
				RRC_Hysteresis_t	 hysteresis;
				RRC_TimeToTrigger_t	 timeToTrigger;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eventA1;
			struct RRC_EventTriggerConfig__eventId__eventA2 {
				RRC_MeasTriggerQuantity_t	 a2_Threshold;
				BOOLEAN_t	 reportOnLeave;
				RRC_Hysteresis_t	 hysteresis;
				RRC_TimeToTrigger_t	 timeToTrigger;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eventA2;
			struct RRC_EventTriggerConfig__eventId__eventA3 {
				RRC_MeasTriggerQuantityOffset_t	 a3_Offset;
				BOOLEAN_t	 reportOnLeave;
				RRC_Hysteresis_t	 hysteresis;
				RRC_TimeToTrigger_t	 timeToTrigger;
				BOOLEAN_t	 useWhiteCellList;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eventA3;
			struct RRC_EventTriggerConfig__eventId__eventA4 {
				RRC_MeasTriggerQuantity_t	 a4_Threshold;
				BOOLEAN_t	 reportOnLeave;
				RRC_Hysteresis_t	 hysteresis;
				RRC_TimeToTrigger_t	 timeToTrigger;
				BOOLEAN_t	 useWhiteCellList;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eventA4;
			struct RRC_EventTriggerConfig__eventId__eventA5 {
				RRC_MeasTriggerQuantity_t	 a5_Threshold1;
				RRC_MeasTriggerQuantity_t	 a5_Threshold2;
				BOOLEAN_t	 reportOnLeave;
				RRC_Hysteresis_t	 hysteresis;
				RRC_TimeToTrigger_t	 timeToTrigger;
				BOOLEAN_t	 useWhiteCellList;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eventA5;
			struct RRC_EventTriggerConfig__eventId__eventA6 {
				RRC_MeasTriggerQuantityOffset_t	 a6_Offset;
				BOOLEAN_t	 reportOnLeave;
				RRC_Hysteresis_t	 hysteresis;
				RRC_TimeToTrigger_t	 timeToTrigger;
				BOOLEAN_t	 useWhiteCellList;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eventA6;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} eventId;
	RRC_NR_RS_Type_t	 rsType;
	RRC_ReportInterval_t	 reportInterval;
	long	 reportAmount;
	RRC_MeasReportQuantity_t	 reportQuantityCell;
	long	 maxReportCells;
	struct RRC_MeasReportQuantity	*reportQuantityRS_Indexes;	/* OPTIONAL */
	long	*maxNrofRS_IndexesToReport;	/* OPTIONAL */
	BOOLEAN_t	 includeBeamMeasurements;
	long	*reportAddNeighMeas;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_EventTriggerConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_reportAmount_41;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_reportAddNeighMeas_55;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRC_EventTriggerConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_EventTriggerConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_EventTriggerConfig_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_EventTriggerConfig_H_ */
#include <asn_internal.h>
