/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_QCL_Info_H_
#define	_RRC_QCL_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC_ServCellIndex.h"
#include "RRC_BWP-Id.h"
#include <NativeEnumerated.h>
#include "RRC_NZP-CSI-RS-ResourceId.h"
#include "RRC_SSB-Index.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_QCL_Info__referenceSignal_PR {
	RRC_QCL_Info__referenceSignal_PR_NOTHING,	/* No components present */
	RRC_QCL_Info__referenceSignal_PR_csi_rs,
	RRC_QCL_Info__referenceSignal_PR_ssb
} RRC_QCL_Info__referenceSignal_PR;
typedef enum RRC_QCL_Info__qcl_Type {
	RRC_QCL_Info__qcl_Type_typeA	= 0,
	RRC_QCL_Info__qcl_Type_typeB	= 1,
	RRC_QCL_Info__qcl_Type_typeC	= 2,
	RRC_QCL_Info__qcl_Type_typeD	= 3
} e_RRC_QCL_Info__qcl_Type;

/* RRC_QCL-Info */
typedef struct RRC_QCL_Info {
	RRC_ServCellIndex_t	*cell;	/* OPTIONAL */
	RRC_BWP_Id_t	*bwp_Id;	/* OPTIONAL */
	struct RRC_QCL_Info__referenceSignal {
		RRC_QCL_Info__referenceSignal_PR present;
		union RRC_QCL_Info__RRC_referenceSignal_u {
			RRC_NZP_CSI_RS_ResourceId_t	 csi_rs;
			RRC_SSB_Index_t	 ssb;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} referenceSignal;
	long	 qcl_Type;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_QCL_Info_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_qcl_Type_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRC_QCL_Info;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_QCL_Info_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_QCL_Info_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_QCL_Info_H_ */
#include <asn_internal.h>
