/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_SRS_SpatialRelationInfo_H_
#define	_RRC_SRS_SpatialRelationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC_ServCellIndex.h"
#include "RRC_SSB-Index.h"
#include "RRC_NZP-CSI-RS-ResourceId.h"
#include "RRC_SRS-ResourceId.h"
#include "RRC_BWP-Id.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_SRS_SpatialRelationInfo__referenceSignal_PR {
	RRC_SRS_SpatialRelationInfo__referenceSignal_PR_NOTHING,	/* No components present */
	RRC_SRS_SpatialRelationInfo__referenceSignal_PR_ssb_Index,
	RRC_SRS_SpatialRelationInfo__referenceSignal_PR_csi_RS_Index,
	RRC_SRS_SpatialRelationInfo__referenceSignal_PR_srs
} RRC_SRS_SpatialRelationInfo__referenceSignal_PR;

/* RRC_SRS-SpatialRelationInfo */
typedef struct RRC_SRS_SpatialRelationInfo {
	RRC_ServCellIndex_t	*servingCellId;	/* OPTIONAL */
	struct RRC_SRS_SpatialRelationInfo__referenceSignal {
		RRC_SRS_SpatialRelationInfo__referenceSignal_PR present;
		union RRC_SRS_SpatialRelationInfo__RRC_referenceSignal_u {
			RRC_SSB_Index_t	 ssb_Index;
			RRC_NZP_CSI_RS_ResourceId_t	 csi_RS_Index;
			struct RRC_SRS_SpatialRelationInfo__referenceSignal__srs {
				RRC_SRS_ResourceId_t	 resourceId;
				RRC_BWP_Id_t	 uplinkBWP;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *srs;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} referenceSignal;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_SRS_SpatialRelationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRC_SRS_SpatialRelationInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_SRS_SpatialRelationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_SRS_SpatialRelationInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_SRS_SpatialRelationInfo_H_ */
#include <asn_internal.h>
