/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_QuantityConfig_H_
#define	_RRC_QuantityConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RRC_QuantityConfigNR;
struct RRC_FilterConfig;

/* RRC_QuantityConfig */
typedef struct RRC_QuantityConfig {
	struct RRC_QuantityConfig__quantityConfigNR_List {
		A_SEQUENCE_OF(struct RRC_QuantityConfigNR) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *quantityConfigNR_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RRC_QuantityConfig__ext1 {
		struct RRC_FilterConfig	*quantityConfigEUTRA;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_QuantityConfig_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRC_QuantityConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_QuantityConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_QuantityConfig_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_QuantityConfig_H_ */
#include <asn_internal.h>
