/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_RadioLinkMonitoringConfig_H_
#define	_RRC_RadioLinkMonitoringConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "RRC_RadioLinkMonitoringRS-Id.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount {
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n1	= 0,
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n2	= 1,
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n3	= 2,
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n4	= 3,
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n5	= 4,
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n6	= 5,
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n8	= 6,
	RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount_n10	= 7
} e_RRC_RadioLinkMonitoringConfig__beamFailureInstanceMaxCount;
typedef enum RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer {
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd1	= 0,
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd2	= 1,
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd3	= 2,
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd4	= 3,
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd5	= 4,
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd6	= 5,
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd8	= 6,
	RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer_pbfd10	= 7
} e_RRC_RadioLinkMonitoringConfig__beamFailureDetectionTimer;

/* Forward declarations */
struct RRC_RadioLinkMonitoringRS;

/* RRC_RadioLinkMonitoringConfig */
typedef struct RRC_RadioLinkMonitoringConfig {
	struct RRC_RadioLinkMonitoringConfig__failureDetectionResourcesToAddModList {
		A_SEQUENCE_OF(struct RRC_RadioLinkMonitoringRS) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *failureDetectionResourcesToAddModList;
	struct RRC_RadioLinkMonitoringConfig__failureDetectionResourcesToReleaseList {
		A_SEQUENCE_OF(RRC_RadioLinkMonitoringRS_Id_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *failureDetectionResourcesToReleaseList;
	long	*beamFailureInstanceMaxCount;	/* OPTIONAL */
	long	*beamFailureDetectionTimer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_RadioLinkMonitoringConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_beamFailureInstanceMaxCount_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_beamFailureDetectionTimer_15;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRC_RadioLinkMonitoringConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_RadioLinkMonitoringConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_RadioLinkMonitoringConfig_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_RadioLinkMonitoringConfig_H_ */
#include <asn_internal.h>
