/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_PUSCH_PathlossReferenceRS_H_
#define	_RRC_PUSCH_PathlossReferenceRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRC_PUSCH-PathlossReferenceRS-Id.h"
#include "RRC_SSB-Index.h"
#include "RRC_NZP-CSI-RS-ResourceId.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_PUSCH_PathlossReferenceRS__referenceSignal_PR {
	RRC_PUSCH_PathlossReferenceRS__referenceSignal_PR_NOTHING,	/* No components present */
	RRC_PUSCH_PathlossReferenceRS__referenceSignal_PR_ssb_Index,
	RRC_PUSCH_PathlossReferenceRS__referenceSignal_PR_csi_RS_Index
} RRC_PUSCH_PathlossReferenceRS__referenceSignal_PR;

/* RRC_PUSCH-PathlossReferenceRS */
typedef struct RRC_PUSCH_PathlossReferenceRS {
	RRC_PUSCH_PathlossReferenceRS_Id_t	 pusch_PathlossReferenceRS_Id;
	struct RRC_PUSCH_PathlossReferenceRS__referenceSignal {
		RRC_PUSCH_PathlossReferenceRS__referenceSignal_PR present;
		union RRC_PUSCH_PathlossReferenceRS__RRC_referenceSignal_u {
			RRC_SSB_Index_t	 ssb_Index;
			RRC_NZP_CSI_RS_ResourceId_t	 csi_RS_Index;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} referenceSignal;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_PUSCH_PathlossReferenceRS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRC_PUSCH_PathlossReferenceRS;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_PUSCH_PathlossReferenceRS_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_PUSCH_PathlossReferenceRS_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_PUSCH_PathlossReferenceRS_H_ */
#include <asn_internal.h>
