/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "asn/nr-rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D rrc`
 */

#ifndef	_RRC_RateMatchPatternLTE_CRS_H_
#define	_RRC_RateMatchPatternLTE_CRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL {
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_n6	= 0,
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_n15	= 1,
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_n25	= 2,
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_n50	= 3,
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_n75	= 4,
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_n100	= 5,
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_spare2	= 6,
	RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL_spare1	= 7
} e_RRC_RateMatchPatternLTE_CRS__carrierBandwidthDL;
typedef enum RRC_RateMatchPatternLTE_CRS__nrofCRS_Ports {
	RRC_RateMatchPatternLTE_CRS__nrofCRS_Ports_n1	= 0,
	RRC_RateMatchPatternLTE_CRS__nrofCRS_Ports_n2	= 1,
	RRC_RateMatchPatternLTE_CRS__nrofCRS_Ports_n4	= 2
} e_RRC_RateMatchPatternLTE_CRS__nrofCRS_Ports;
typedef enum RRC_RateMatchPatternLTE_CRS__v_Shift {
	RRC_RateMatchPatternLTE_CRS__v_Shift_n0	= 0,
	RRC_RateMatchPatternLTE_CRS__v_Shift_n1	= 1,
	RRC_RateMatchPatternLTE_CRS__v_Shift_n2	= 2,
	RRC_RateMatchPatternLTE_CRS__v_Shift_n3	= 3,
	RRC_RateMatchPatternLTE_CRS__v_Shift_n4	= 4,
	RRC_RateMatchPatternLTE_CRS__v_Shift_n5	= 5
} e_RRC_RateMatchPatternLTE_CRS__v_Shift;

/* Forward declarations */
struct RRC_EUTRA_MBSFN_SubframeConfigList;

/* RRC_RateMatchPatternLTE-CRS */
typedef struct RRC_RateMatchPatternLTE_CRS {
	long	 carrierFreqDL;
	long	 carrierBandwidthDL;
	struct RRC_EUTRA_MBSFN_SubframeConfigList	*mbsfn_SubframeConfigList;	/* OPTIONAL */
	long	 nrofCRS_Ports;
	long	 v_Shift;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRC_RateMatchPatternLTE_CRS_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_carrierBandwidthDL_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_nrofCRS_Ports_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_RRC_v_Shift_17;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRC_RateMatchPatternLTE_CRS;
extern asn_SEQUENCE_specifics_t asn_SPC_RRC_RateMatchPatternLTE_CRS_specs_1;
extern asn_TYPE_member_t asn_MBR_RRC_RateMatchPatternLTE_CRS_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RRC_RateMatchPatternLTE_CRS_H_ */
#include <asn_internal.h>
