// Copyright (c) 2020 ALİ GÜNGÖR (aligng1620@gmail.com)
// This software and all associated files are licensed under GPL-3.0.

#pragma once

#include <RRC_AccessStratumRelease.h>
#include <RRC_AdditionalSpectrumEmission.h>
#include <RRC_AffectedCarrierFreqCombEUTRA.h>
#include <RRC_AffectedCarrierFreqCombInfoMRDC.h>
#include <RRC_AffectedCarrierFreqCombNR.h>
#include <RRC_AggregatedBandwidth.h>
#include <RRC_Alpha.h>
#include <RRC_AMF-Identifier.h>
#include <RRC_ARFCN-ValueEUTRA.h>
#include <RRC_ARFCN-ValueNR.h>
#include <RRC_AS-Config.h>
#include <RRC_AS-Context.h>
#include <RRC_asn_constant.h>
#include <RRC_BandCombination.h>
#include <RRC_BandCombinationIndex.h>
#include <RRC_BandCombinationInfo.h>
#include <RRC_BandCombinationInfoList.h>
#include <RRC_BandCombinationInfoSN.h>
#include <RRC_BandCombinationList.h>
#include <RRC_BandCombinationList-v1540.h>
#include <RRC_BandCombinationList-v1550.h>
#include <RRC_BandCombinationList-v1560.h>
#include <RRC_BandCombination-v1540.h>
#include <RRC_BandCombination-v1550.h>
#include <RRC_BandCombination-v1560.h>
#include <RRC_BandEntryIndex.h>
#include <RRC_BandNR.h>
#include <RRC_BandParameters.h>
#include <RRC_BandParameters-v1540.h>
#include <RRC_BCCH-BCH-Message.h>
#include <RRC_BCCH-BCH-MessageType.h>
#include <RRC_BCCH-Config.h>
#include <RRC_BCCH-DL-SCH-Message.h>
#include <RRC_BCCH-DL-SCH-MessageType.h>
#include <RRC_BeamFailureRecoveryConfig.h>
#include <RRC_BeamManagementSSB-CSI-RS.h>
#include <RRC_BetaOffsets.h>
#include <RRC_BFR-CSIRS-Resource.h>
#include <RRC_BFR-SSB-Resource.h>
#include <RRC_BSR-Config.h>
#include <RRC_BWP-DownlinkCommon.h>
#include <RRC_BWP-DownlinkDedicated.h>
#include <RRC_BWP-Downlink.h>
#include <RRC_BWP.h>
#include <RRC_BWP-Id.h>
#include <RRC_BWP-UplinkCommon.h>
#include <RRC_BWP-UplinkDedicated.h>
#include <RRC_BWP-Uplink.h>
#include <RRC_CA-BandwidthClassEUTRA.h>
#include <RRC_CA-BandwidthClassNR.h>
#include <RRC_CandidateServingFreqListEUTRA.h>
#include <RRC_CandidateServingFreqListNR.h>
#include <RRC_CA-ParametersEUTRA.h>
#include <RRC_CA-ParametersEUTRA-v1560.h>
#include <RRC_CA-ParametersNRDC.h>
#include <RRC_CA-ParametersNR.h>
#include <RRC_CA-ParametersNR-v1540.h>
#include <RRC_CA-ParametersNR-v1550.h>
#include <RRC_CA-ParametersNR-v1560.h>
#include <RRC_CarrierFreqEUTRA.h>
#include <RRC_CarrierFreqListEUTRA.h>
#include <RRC_CarrierInfoNR.h>
#include <RRC_CellAccessRelatedInfo-EUTRA-5GC.h>
#include <RRC_CellAccessRelatedInfo-EUTRA-EPC.h>
#include <RRC_CellAccessRelatedInfo.h>
#include <RRC_CellGroupConfig.h>
#include <RRC_CellGroupId.h>
#include <RRC_CellIdentity-EUTRA-5GC.h>
#include <RRC_CellIdentity.h>
#include <RRC_CellReselectionPriorities.h>
#include <RRC_CellReselectionPriority.h>
#include <RRC_CellReselectionSubPriority.h>
#include <RRC_CellsToAddMod.h>
#include <RRC_CellsToAddModList.h>
#include <RRC_CellsTriggeredList.h>
#include <RRC_CFRA-CSIRS-Resource.h>
#include <RRC_CFRA.h>
#include <RRC_CFRA-SSB-Resource.h>
#include <RRC_CG-Config.h>
#include <RRC_CG-Config-IEs.h>
#include <RRC_CG-ConfigInfo.h>
#include <RRC_CG-ConfigInfo-IEs.h>
#include <RRC_CG-ConfigInfo-v1540-IEs.h>
#include <RRC_CG-ConfigInfo-v1560-IEs.h>
#include <RRC_CG-Config-v1540-IEs.h>
#include <RRC_CG-Config-v1560-IEs.h>
#include <RRC_CGI-InfoEUTRA.h>
#include <RRC_CGI-InfoNR.h>
#include <RRC_CG-UCI-OnPUSCH.h>
#include <RRC_CipheringAlgorithm.h>
#include <RRC_CodebookConfig.h>
#include <RRC_CodebookParameters.h>
#include <RRC_ConfigRestrictInfoSCG.h>
#include <RRC_ConfigRestrictModReqSCG.h>
#include <RRC_ConfiguredGrantConfig.h>
#include <RRC_ConnEstFailureControl.h>
#include <RRC_ControlResourceSet.h>
#include <RRC_ControlResourceSetId.h>
#include <RRC_ControlResourceSetZero.h>
#include <RRC_CounterCheck.h>
#include <RRC_CounterCheck-IEs.h>
#include <RRC_CounterCheckResponse.h>
#include <RRC_CounterCheckResponse-IEs.h>
#include <RRC_CrossCarrierSchedulingConfig.h>
#include <RRC_CSI-AperiodicTriggerState.h>
#include <RRC_CSI-AperiodicTriggerStateList.h>
#include <RRC_CSI-AssociatedReportConfigInfo.h>
#include <RRC_CSI-FrequencyOccupation.h>
#include <RRC_CSI-IM-Resource.h>
#include <RRC_CSI-IM-ResourceId.h>
#include <RRC_CSI-IM-ResourceSet.h>
#include <RRC_CSI-IM-ResourceSetId.h>
#include <RRC_CSI-MeasConfig.h>
#include <RRC_CSI-ReportConfig.h>
#include <RRC_CSI-ReportConfigId.h>
#include <RRC_CSI-ReportFramework.h>
#include <RRC_CSI-ReportPeriodicityAndOffset.h>
#include <RRC_CSI-ResourceConfig.h>
#include <RRC_CSI-ResourceConfigId.h>
#include <RRC_CSI-ResourcePeriodicityAndOffset.h>
#include <RRC_CSI-RS-CellMobility.h>
#include <RRC_CSI-RS-ForTracking.h>
#include <RRC_CSI-RS-IM-ReceptionForFeedback.h>
#include <RRC_CSI-RS-Index.h>
#include <RRC_CSI-RS-ProcFrameworkForSRS.h>
#include <RRC_CSI-RS-ResourceConfigMobility.h>
#include <RRC_CSI-RS-ResourceMapping.h>
#include <RRC_CSI-RS-Resource-Mobility.h>
#include <RRC_CSI-SemiPersistentOnPUSCH-TriggerState.h>
#include <RRC_CSI-SemiPersistentOnPUSCH-TriggerStateList.h>
#include <RRC_CSI-SSB-ResourceSet.h>
#include <RRC_CSI-SSB-ResourceSetId.h>
#include <RRC_DataInactivityTimer.h>
#include <RRC_DedicatedNAS-Message.h>
#include <RRC_DelayBudgetReport.h>
#include <RRC_DL-AM-RLC.h>
#include <RRC_DL-CCCH-Message.h>
#include <RRC_DL-CCCH-MessageType.h>
#include <RRC_DL-DCCH-Message.h>
#include <RRC_DL-DCCH-MessageType.h>
#include <RRC_DLInformationTransfer.h>
#include <RRC_DLInformationTransfer-IEs.h>
#include <RRC_DL-UM-RLC.h>
#include <RRC_DMRS-DownlinkConfig.h>
#include <RRC_DMRS-UplinkConfig.h>
#include <RRC_DownlinkConfigCommon.h>
#include <RRC_DownlinkConfigCommonSIB.h>
#include <RRC_DownlinkPreemption.h>
#include <RRC_DRB-CountInfo.h>
#include <RRC_DRB-CountInfoList.h>
#include <RRC_DRB-CountMSB-Info.h>
#include <RRC_DRB-CountMSB-InfoList.h>
#include <RRC_DRB-Identity.h>
#include <RRC_DRB-ToAddMod.h>
#include <RRC_DRB-ToAddModList.h>
#include <RRC_DRB-ToReleaseList.h>
#include <RRC_DRX-Config.h>
#include <RRC_DRX-Info.h>
#include <RRC_DummyA.h>
#include <RRC_DummyB.h>
#include <RRC_DummyC.h>
#include <RRC_DummyD.h>
#include <RRC_DummyE.h>
#include <RRC_DummyF.h>
#include <RRC_DummyG.h>
#include <RRC_DummyH.h>
#include <RRC_DummyI.h>
#include <RRC_EstablishmentCause.h>
#include <RRC_EUTRA-AllowedMeasBandwidth.h>
#include <RRC_EUTRA-BlackCell.h>
#include <RRC_EUTRA-Cell.h>
#include <RRC_EUTRA-CellIndex.h>
#include <RRC_EUTRA-CellIndexList.h>
#include <RRC_EUTRA-FreqBlackCellList.h>
#include <RRC_EUTRA-FreqNeighCellInfo.h>
#include <RRC_EUTRA-FreqNeighCellList.h>
#include <RRC_EUTRA-MBSFN-SubframeConfig.h>
#include <RRC_EUTRA-MBSFN-SubframeConfigList.h>
#include <RRC_EUTRA-MultiBandInfo.h>
#include <RRC_EUTRA-MultiBandInfoList.h>
#include <RRC_EUTRA-NS-PmaxList.h>
#include <RRC_EUTRA-NS-PmaxValue.h>
#include <RRC_EUTRA-ParametersCommon.h>
#include <RRC_EUTRA-Parameters.h>
#include <RRC_EUTRA-ParametersXDD-Diff.h>
#include <RRC_EUTRA-PhysCellId.h>
#include <RRC_EUTRA-PhysCellIdRange.h>
#include <RRC_EUTRA-PresenceAntennaPort1.h>
#include <RRC_EUTRA-Q-OffsetRange.h>
#include <RRC_EUTRA-RSTD-Info.h>
#include <RRC_EUTRA-RSTD-InfoList.h>
#include <RRC_EventTriggerConfig.h>
#include <RRC_EventTriggerConfigInterRAT.h>
#include <RRC_FailureInfoRLC-Bearer.h>
#include <RRC_FailureInformation.h>
#include <RRC_FailureInformation-IEs.h>
#include <RRC_FailureReportSCG-EUTRA.h>
#include <RRC_FailureReportSCG.h>
#include <RRC_FeatureSetCombination.h>
#include <RRC_FeatureSetCombinationId.h>
#include <RRC_FeatureSetDownlink.h>
#include <RRC_FeatureSetDownlinkId.h>
#include <RRC_FeatureSetDownlinkPerCC.h>
#include <RRC_FeatureSetDownlinkPerCC-Id.h>
#include <RRC_FeatureSetDownlink-v1540.h>
#include <RRC_FeatureSetEntryIndex.h>
#include <RRC_FeatureSetEUTRA-DownlinkId.h>
#include <RRC_FeatureSetEUTRA-UplinkId.h>
#include <RRC_FeatureSet.h>
#include <RRC_FeatureSets.h>
#include <RRC_FeatureSetsPerBand.h>
#include <RRC_FeatureSetUplink.h>
#include <RRC_FeatureSetUplinkId.h>
#include <RRC_FeatureSetUplinkPerCC.h>
#include <RRC_FeatureSetUplinkPerCC-Id.h>
#include <RRC_FeatureSetUplinkPerCC-v1540.h>
#include <RRC_FeatureSetUplink-v1540.h>
#include <RRC_FilterCoefficient.h>
#include <RRC_FilterConfig.h>
#include <RRC_FreqBandIndicatorEUTRA.h>
#include <RRC_FreqBandIndicatorNR.h>
#include <RRC_FreqBandInformationEUTRA.h>
#include <RRC_FreqBandInformation.h>
#include <RRC_FreqBandInformationNR.h>
#include <RRC_FreqBandList.h>
#include <RRC_FreqPriorityEUTRA.h>
#include <RRC_FreqPriorityListEUTRA.h>
#include <RRC_FreqPriorityListNR.h>
#include <RRC_FreqPriorityNR.h>
#include <RRC_FreqSeparationClass.h>
#include <RRC_FrequencyInfoDL.h>
#include <RRC_FrequencyInfoDL-SIB.h>
#include <RRC_FrequencyInfoUL.h>
#include <RRC_FrequencyInfoUL-SIB.h>
#include <RRC_FR-Info.h>
#include <RRC_FR-InfoList.h>
#include <RRC_GapConfig.h>
#include <RRC_GeneralParametersMRDC-XDD-Diff.h>
#include <RRC_HandoverCommand.h>
#include <RRC_HandoverCommand-IEs.h>
#include <RRC_HandoverPreparationInformation.h>
#include <RRC_HandoverPreparationInformation-IEs.h>
#include <RRC_Hysteresis.h>
#include <RRC_IMS-ParametersCommon.h>
#include <RRC_IMS-ParametersFRX-Diff.h>
#include <RRC_IMS-Parameters.h>
#include <RRC_InitialUE-Identity.h>
#include <RRC_INT-ConfigurationPerServingCell.h>
#include <RRC_IntegrityProtAlgorithm.h>
#include <RRC_InterFreqBlackCellList.h>
#include <RRC_InterFreqCarrierFreqInfo.h>
#include <RRC_InterFreqCarrierFreqList.h>
#include <RRC_InterFreqNeighCellInfo.h>
#include <RRC_InterFreqNeighCellList.h>
#include <RRC_InterRAT-Parameters.h>
#include <RRC_IntraFreqBlackCellList.h>
#include <RRC_IntraFreqNeighCellInfo.h>
#include <RRC_IntraFreqNeighCellList.h>
#include <RRC_I-RNTI-Value.h>
#include <RRC_LocationMeasurementIndication.h>
#include <RRC_LocationMeasurementIndication-IEs.h>
#include <RRC_LocationMeasurementInfo.h>
#include <RRC_LogicalChannelConfig.h>
#include <RRC_LogicalChannelIdentity.h>
#include <RRC_MAC-CellGroupConfig.h>
#include <RRC_MAC-ParametersCommon.h>
#include <RRC_MAC-Parameters.h>
#include <RRC_MAC-ParametersXDD-Diff.h>
#include <RRC_MasterKeyUpdate.h>
#include <RRC_MCC.h>
#include <RRC_MCC-MNC-Digit.h>
#include <RRC_MeasAndMobParametersCommon.h>
#include <RRC_MeasAndMobParametersFRX-Diff.h>
#include <RRC_MeasAndMobParameters.h>
#include <RRC_MeasAndMobParametersMRDC-Common.h>
#include <RRC_MeasAndMobParametersMRDC-FRX-Diff.h>
#include <RRC_MeasAndMobParametersMRDC.h>
#include <RRC_MeasAndMobParametersMRDC-v1560.h>
#include <RRC_MeasAndMobParametersMRDC-XDD-Diff.h>
#include <RRC_MeasAndMobParametersMRDC-XDD-Diff-v1560.h>
#include <RRC_MeasAndMobParametersXDD-Diff.h>
#include <RRC_MeasConfig.h>
#include <RRC_MeasConfigMN.h>
#include <RRC_MeasConfigSN.h>
#include <RRC_MeasGapConfig.h>
#include <RRC_MeasGapSharingConfig.h>
#include <RRC_MeasGapSharingScheme.h>
#include <RRC_MeasId.h>
#include <RRC_MeasIdToAddMod.h>
#include <RRC_MeasIdToAddModList.h>
#include <RRC_MeasIdToRemoveList.h>
#include <RRC_MeasObjectEUTRA.h>
#include <RRC_MeasObjectId.h>
#include <RRC_MeasObjectNR.h>
#include <RRC_MeasObjectToAddMod.h>
#include <RRC_MeasObjectToAddModList.h>
#include <RRC_MeasObjectToRemoveList.h>
#include <RRC_MeasQuantityResultsEUTRA.h>
#include <RRC_MeasQuantityResults.h>
#include <RRC_MeasReportQuantity.h>
#include <RRC_MeasResult2EUTRA.h>
#include <RRC_MeasResult2NR.h>
#include <RRC_MeasResultCellListSFTD-EUTRA.h>
#include <RRC_MeasResultCellListSFTD-NR.h>
#include <RRC_MeasResultCellSFTD-NR.h>
#include <RRC_MeasResultEUTRA.h>
#include <RRC_MeasResultFreqListFailMRDC.h>
#include <RRC_MeasResultFreqList.h>
#include <RRC_MeasResultList2NR.h>
#include <RRC_MeasResultListEUTRA.h>
#include <RRC_MeasResultListNR.h>
#include <RRC_MeasResultNR.h>
#include <RRC_MeasResultSCG-Failure.h>
#include <RRC_MeasResultServFreqListEUTRA-SCG.h>
#include <RRC_MeasResultServFreqListNR-SCG.h>
#include <RRC_MeasResultServMO.h>
#include <RRC_MeasResultServMOList.h>
#include <RRC_MeasResultSFTD-EUTRA.h>
#include <RRC_MeasResults.h>
#include <RRC_MeasTiming.h>
#include <RRC_MeasTimingList.h>
#include <RRC_MeasTriggerQuantityEUTRA.h>
#include <RRC_MeasTriggerQuantity.h>
#include <RRC_MeasTriggerQuantityOffset.h>
#include <RRC_MeasurementReport.h>
#include <RRC_MeasurementReport-IEs.h>
#include <RRC_MeasurementTimingConfiguration.h>
#include <RRC_MeasurementTimingConfiguration-IEs.h>
#include <RRC_MeasurementTimingConfiguration-v1550-IEs.h>
#include <RRC_MIB.h>
#include <RRC_MIMO-LayersDL.h>
#include <RRC_MIMO-LayersUL.h>
#include <RRC_MIMO-ParametersPerBand.h>
#include <RRC_MNC.h>
#include <RRC_MobilityFromNRCommand.h>
#include <RRC_MobilityFromNRCommand-IEs.h>
#include <RRC_MobilityStateParameters.h>
#include <RRC_ModulationOrder.h>
#include <RRC_MRDC-AssistanceInfo.h>
#include <RRC_MRDC-Parameters.h>
#include <RRC_MRDC-SecondaryCellGroupConfig.h>
#include <RRC_MultiBandInfoListEUTRA.h>
#include <RRC_MultiFrequencyBandListNR.h>
#include <RRC_MultiFrequencyBandListNR-SIB.h>
#include <RRC_NAICS-Capability-Entry.h>
#include <RRC_NextHopChainingCount.h>
#include <RRC_NG-5G-S-TMSI.h>
#include <RRC_NRDC-Parameters.h>
#include <RRC_NR-FreqInfo.h>
#include <RRC_NR-MultiBandInfo.h>
#include <RRC_NR-NS-PmaxList.h>
#include <RRC_NR-NS-PmaxValue.h>
#include <RRC_NR-RS-Type.h>
#include <RRC_NumberOfCarriers.h>
#include <RRC_NZP-CSI-RS-Resource.h>
#include <RRC_NZP-CSI-RS-ResourceId.h>
#include <RRC_NZP-CSI-RS-ResourceSet.h>
#include <RRC_NZP-CSI-RS-ResourceSetId.h>
#include <RRC_OtherConfig.h>
#include <RRC_OtherConfig-v1540.h>
#include <RRC_OverheatingAssistanceConfig.h>
#include <RRC_OverheatingAssistance.h>
#include <RRC_P0-PUCCH.h>
#include <RRC_P0-PUCCH-Id.h>
#include <RRC_P0-PUSCH-AlphaSet.h>
#include <RRC_P0-PUSCH-AlphaSetId.h>
#include <RRC_PagingCycle.h>
#include <RRC_Paging.h>
#include <RRC_PagingRecord.h>
#include <RRC_PagingRecordList.h>
#include <RRC_PagingUE-Identity.h>
#include <RRC_PCCH-Config.h>
#include <RRC_PCCH-Message.h>
#include <RRC_PCCH-MessageType.h>
#include <RRC_PCI-List.h>
#include <RRC_PCI-RangeElement.h>
#include <RRC_PCI-Range.h>
#include <RRC_PCI-RangeIndex.h>
#include <RRC_PCI-RangeIndexList.h>
#include <RRC_PDCCH-BlindDetection.h>
#include <RRC_PDCCH-ConfigCommon.h>
#include <RRC_PDCCH-Config.h>
#include <RRC_PDCCH-ConfigSIB1.h>
#include <RRC_PDCCH-ServingCellConfig.h>
#include <RRC_PDCP-Config.h>
#include <RRC_PDCP-Parameters.h>
#include <RRC_PDCP-ParametersMRDC.h>
#include <RRC_PDSCH-CodeBlockGroupTransmission.h>
#include <RRC_PDSCH-ConfigCommon.h>
#include <RRC_PDSCH-Config.h>
#include <RRC_PDSCH-ServingCellConfig.h>
#include <RRC_PDSCH-TimeDomainResourceAllocation.h>
#include <RRC_PDSCH-TimeDomainResourceAllocationList.h>
#include <RRC_PDU-SessionID.h>
#include <RRC_PeriodicalReportConfig.h>
#include <RRC_PeriodicalReportConfigInterRAT.h>
#include <RRC_PeriodicRNAU-TimerValue.h>
#include <RRC_PH-InfoMCG.h>
#include <RRC_PH-InfoSCG.h>
#include <RRC_PHR-Config.h>
#include <RRC_PH-TypeListMCG.h>
#include <RRC_PH-TypeListSCG.h>
#include <RRC_PH-UplinkCarrierMCG.h>
#include <RRC_PH-UplinkCarrierSCG.h>
#include <RRC_Phy-ParametersCommon.h>
#include <RRC_Phy-ParametersFR1.h>
#include <RRC_Phy-ParametersFR2.h>
#include <RRC_Phy-ParametersFRX-Diff.h>
#include <RRC_Phy-Parameters.h>
#include <RRC_Phy-ParametersMRDC.h>
#include <RRC_Phy-ParametersXDD-Diff.h>
#include <RRC_PhysCellId.h>
#include <RRC_PhysicalCellGroupConfig.h>
#include <RRC_PLMN-Identity-EUTRA-5GC.h>
#include <RRC_PLMN-Identity.h>
#include <RRC_PLMN-IdentityInfo.h>
#include <RRC_PLMN-IdentityInfoList.h>
#include <RRC_PLMN-IdentityList-EUTRA-5GC.h>
#include <RRC_PLMN-IdentityList-EUTRA-EPC.h>
#include <RRC_PLMN-RAN-AreaCell.h>
#include <RRC_PLMN-RAN-AreaCellList.h>
#include <RRC_PLMN-RAN-AreaConfig.h>
#include <RRC_PLMN-RAN-AreaConfigList.h>
#include <RRC_P-Max.h>
#include <RRC_PollByte.h>
#include <RRC_PollPDU.h>
#include <RRC_PortIndex2.h>
#include <RRC_PortIndex4.h>
#include <RRC_PortIndex8.h>
#include <RRC_PortIndexFor8Ranks.h>
#include <RRC_PRACH-ResourceDedicatedBFR.h>
#include <RRC_PRB-Id.h>
#include <RRC_ProcessingParameters.h>
#include <RRC_PTRS-DensityRecommendationDL.h>
#include <RRC_PTRS-DensityRecommendationUL.h>
#include <RRC_PTRS-DownlinkConfig.h>
#include <RRC_PTRS-UplinkConfig.h>
#include <RRC_PUCCH-ConfigCommon.h>
#include <RRC_PUCCH-Config.h>
#include <RRC_PUCCH-CSI-Resource.h>
#include <RRC_PUCCH-format0.h>
#include <RRC_PUCCH-format1.h>
#include <RRC_PUCCH-format2.h>
#include <RRC_PUCCH-format3.h>
#include <RRC_PUCCH-format4.h>
#include <RRC_PUCCH-FormatConfig.h>
#include <RRC_PUCCH-MaxCodeRate.h>
#include <RRC_PUCCH-PathlossReferenceRS.h>
#include <RRC_PUCCH-PathlossReferenceRS-Id.h>
#include <RRC_PUCCH-PowerControl.h>
#include <RRC_PUCCH-Resource.h>
#include <RRC_PUCCH-ResourceId.h>
#include <RRC_PUCCH-ResourceSet.h>
#include <RRC_PUCCH-ResourceSetId.h>
#include <RRC_PUCCH-SpatialRelationInfo.h>
#include <RRC_PUCCH-SpatialRelationInfoId.h>
#include <RRC_PUCCH-TPC-CommandConfig.h>
#include <RRC_PUSCH-CodeBlockGroupTransmission.h>
#include <RRC_PUSCH-ConfigCommon.h>
#include <RRC_PUSCH-Config.h>
#include <RRC_PUSCH-PathlossReferenceRS.h>
#include <RRC_PUSCH-PathlossReferenceRS-Id.h>
#include <RRC_PUSCH-PowerControl.h>
#include <RRC_PUSCH-ServingCellConfig.h>
#include <RRC_PUSCH-TimeDomainResourceAllocation.h>
#include <RRC_PUSCH-TimeDomainResourceAllocationList.h>
#include <RRC_PUSCH-TPC-CommandConfig.h>
#include <RRC_QCL-Info.h>
#include <RRC_QFI.h>
#include <RRC_Q-OffsetRange.h>
#include <RRC_Q-OffsetRangeList.h>
#include <RRC_Q-QualMin.h>
#include <RRC_Q-RxLevMin.h>
#include <RRC_QuantityConfig.h>
#include <RRC_QuantityConfigNR.h>
#include <RRC_QuantityConfigRS.h>
#include <RRC_RACH-ConfigCommon.h>
#include <RRC_RACH-ConfigDedicated.h>
#include <RRC_RACH-ConfigGeneric.h>
#include <RRC_RadioBearerConfig.h>
#include <RRC_RadioLinkMonitoringConfig.h>
#include <RRC_RadioLinkMonitoringRS.h>
#include <RRC_RadioLinkMonitoringRS-Id.h>
#include <RRC_RAN-AreaCode.h>
#include <RRC_RAN-AreaConfig.h>
#include <RRC_RangeToBestCell.h>
#include <RRC_RAN-NotificationAreaInfo.h>
#include <RRC_RA-Prioritization.h>
#include <RRC_RateMatchPatternGroup.h>
#include <RRC_RateMatchPattern.h>
#include <RRC_RateMatchPatternId.h>
#include <RRC_RateMatchPatternLTE-CRS.h>
#include <RRC_RAT-Type.h>
#include <RRC_ReconfigurationWithSync.h>
#include <RRC_RedirectedCarrierInfo-EUTRA.h>
#include <RRC_RedirectedCarrierInfo.h>
#include <RRC_ReducedAggregatedBandwidth.h>
#include <RRC_ReestablishmentCause.h>
#include <RRC_ReestablishmentInfo.h>
#include <RRC_ReestabNCellInfo.h>
#include <RRC_ReestabNCellInfoList.h>
#include <RRC_ReestabUE-Identity.h>
#include <RRC_ReferenceSignalConfig.h>
#include <RRC_RegisteredAMF.h>
#include <RRC_RejectWaitTime.h>
#include <RRC_ReportCGI-EUTRA.h>
#include <RRC_ReportCGI.h>
#include <RRC_ReportConfigId.h>
#include <RRC_ReportConfigInterRAT.h>
#include <RRC_ReportConfigNR.h>
#include <RRC_ReportConfigToAddMod.h>
#include <RRC_ReportConfigToAddModList.h>
#include <RRC_ReportConfigToRemoveList.h>
#include <RRC_ReportInterval.h>
#include <RRC_ReportSFTD-EUTRA.h>
#include <RRC_ReportSFTD-NR.h>
#include <RRC_ReselectionThreshold.h>
#include <RRC_ReselectionThresholdQ.h>
#include <RRC_ResultsPerCSI-RS-Index.h>
#include <RRC_ResultsPerCSI-RS-IndexList.h>
#include <RRC_ResultsPerSSB-Index.h>
#include <RRC_ResultsPerSSB-IndexList.h>
#include <RRC_ResumeCause.h>
#include <RRC_RF-Parameters.h>
#include <RRC_RF-ParametersMRDC.h>
#include <RRC_RLC-BearerConfig.h>
#include <RRC_RLC-Config.h>
#include <RRC_RLC-Parameters.h>
#include <RRC_RLF-TimersAndConstants.h>
#include <RRC_RNTI-Value.h>
#include <RRC_RRCReconfigurationComplete.h>
#include <RRC_RRCReconfigurationComplete-IEs.h>
#include <RRC_RRCReconfigurationComplete-v1530-IEs.h>
#include <RRC_RRCReconfigurationComplete-v1560-IEs.h>
#include <RRC_RRCReconfiguration.h>
#include <RRC_RRCReconfiguration-IEs.h>
#include <RRC_RRCReconfiguration-v1530-IEs.h>
#include <RRC_RRCReconfiguration-v1540-IEs.h>
#include <RRC_RRCReconfiguration-v1560-IEs.h>
#include <RRC_RRCReestablishmentComplete.h>
#include <RRC_RRCReestablishmentComplete-IEs.h>
#include <RRC_RRCReestablishment.h>
#include <RRC_RRCReestablishment-IEs.h>
#include <RRC_RRCReestablishmentRequest.h>
#include <RRC_RRCReestablishmentRequest-IEs.h>
#include <RRC_RRCReject.h>
#include <RRC_RRCReject-IEs.h>
#include <RRC_RRCRelease.h>
#include <RRC_RRCRelease-IEs.h>
#include <RRC_RRCRelease-v1540-IEs.h>
#include <RRC_RRCResumeComplete.h>
#include <RRC_RRCResumeComplete-IEs.h>
#include <RRC_RRCResume.h>
#include <RRC_RRCResume-IEs.h>
#include <RRC_RRCResumeRequest1.h>
#include <RRC_RRCResumeRequest1-IEs.h>
#include <RRC_RRCResumeRequest.h>
#include <RRC_RRCResumeRequest-IEs.h>
#include <RRC_RRCResume-v1560-IEs.h>
#include <RRC_RRCSetupComplete.h>
#include <RRC_RRCSetupComplete-IEs.h>
#include <RRC_RRCSetup.h>
#include <RRC_RRCSetup-IEs.h>
#include <RRC_RRCSetupRequest.h>
#include <RRC_RRCSetupRequest-IEs.h>
#include <RRC_RRCSystemInfoRequest.h>
#include <RRC_RRCSystemInfoRequest-r15-IEs.h>
#include <RRC_RRC-TransactionIdentifier.h>
#include <RRC_RRM-Config.h>
#include <RRC_RSRP-RangeEUTRA.h>
#include <RRC_RSRP-Range.h>
#include <RRC_RSRQ-RangeEUTRA.h>
#include <RRC_RSRQ-Range.h>
#include <RRC_SCellConfig.h>
#include <RRC_SCellIndex.h>
#include <RRC_SCGFailureInformationEUTRA.h>
#include <RRC_SCGFailureInformationEUTRA-IEs.h>
#include <RRC_SCGFailureInformation.h>
#include <RRC_SCGFailureInformation-IEs.h>
#include <RRC_SchedulingInfo.h>
#include <RRC_SchedulingRequestConfig.h>
#include <RRC_SchedulingRequestId.h>
#include <RRC_SchedulingRequestResourceConfig.h>
#include <RRC_SchedulingRequestResourceId.h>
#include <RRC_SchedulingRequestToAddMod.h>
#include <RRC_ScramblingId.h>
#include <RRC_SCS-SpecificCarrier.h>
#include <RRC_SDAP-Config.h>
#include <RRC_SDAP-Parameters.h>
#include <RRC_SearchSpace.h>
#include <RRC_SearchSpaceId.h>
#include <RRC_SearchSpaceZero.h>
#include <RRC_SecurityAlgorithmConfig.h>
#include <RRC_SecurityConfig.h>
#include <RRC_SecurityConfigSMC.h>
#include <RRC_SecurityModeCommand.h>
#include <RRC_SecurityModeCommand-IEs.h>
#include <RRC_SecurityModeComplete.h>
#include <RRC_SecurityModeComplete-IEs.h>
#include <RRC_SecurityModeFailure.h>
#include <RRC_SecurityModeFailure-IEs.h>
#include <RRC_ServCellIndex.h>
#include <RRC_ServingCellConfigCommon.h>
#include <RRC_ServingCellConfigCommonSIB.h>
#include <RRC_ServingCellConfig.h>
#include <RRC_SetupRelease.h>
#include <RRC_ShortI-RNTI-Value.h>
#include <RRC_ShortMAC-I.h>
#include <RRC_SIB1.h>
#include <RRC_SIB2.h>
#include <RRC_SIB3.h>
#include <RRC_SIB4.h>
#include <RRC_SIB5.h>
#include <RRC_SIB6.h>
#include <RRC_SIB7.h>
#include <RRC_SIB8.h>
#include <RRC_SIB9.h>
#include <RRC_SIB-Mapping.h>
#include <RRC_SIB-TypeInfo.h>
#include <RRC_SINR-RangeEUTRA.h>
#include <RRC_SINR-Range.h>
#include <RRC_SI-RequestConfig.h>
#include <RRC_SI-RequestResources.h>
#include <RRC_SI-SchedulingInfo.h>
#include <RRC_SK-Counter.h>
#include <RRC_SlotFormatCombination.h>
#include <RRC_SlotFormatCombinationId.h>
#include <RRC_SlotFormatCombinationsPerCell.h>
#include <RRC_SlotFormatIndicator.h>
#include <RRC_SN-FieldLengthAM.h>
#include <RRC_SN-FieldLengthUM.h>
#include <RRC_S-NSSAI.h>
#include <RRC_SpatialRelations.h>
#include <RRC_SpCellConfig.h>
#include <RRC_SpeedStateScaleFactors.h>
#include <RRC_SPS-Config.h>
#include <RRC_SRB-Identity.h>
#include <RRC_SRB-ToAddMod.h>
#include <RRC_SRB-ToAddModList.h>
#include <RRC_SRI-PUSCH-PowerControl.h>
#include <RRC_SRI-PUSCH-PowerControlId.h>
#include <RRC_SRS-CarrierSwitching.h>
#include <RRC_SRS-CC-SetIndex.h>
#include <RRC_SRS-Config.h>
#include <RRC_SRS-PeriodicityAndOffset.h>
#include <RRC_SRS-Resource.h>
#include <RRC_SRS-ResourceId.h>
#include <RRC_SRS-ResourceSet.h>
#include <RRC_SRS-ResourceSetId.h>
#include <RRC_SRS-Resources.h>
#include <RRC_SRS-SpatialRelationInfo.h>
#include <RRC_SRS-SwitchingTimeEUTRA.h>
#include <RRC_SRS-SwitchingTimeNR.h>
#include <RRC_SRS-TPC-CommandConfig.h>
#include <RRC_SRS-TPC-PDCCH-Config.h>
#include <RRC_SSB-ConfigMobility.h>
#include <RRC_SSB-Index.h>
#include <RRC_SSB-MTC2.h>
#include <RRC_SSB-MTC.h>
#include <RRC_SSB-ToMeasure.h>
#include <RRC_SS-RSSI-Measurement.h>
#include <RRC_SubcarrierSpacing.h>
#include <RRC_SupportedBandwidth.h>
#include <RRC_SupportedCSI-RS-Resource.h>
#include <RRC_SuspendConfig.h>
#include <RRC_SystemInformation.h>
#include <RRC_SystemInformation-IEs.h>
#include <RRC_TAG-Config.h>
#include <RRC_TAG.h>
#include <RRC_TAG-Id.h>
#include <RRC_TCI-State.h>
#include <RRC_TCI-StateId.h>
#include <RRC_TDD-UL-DL-ConfigCommon.h>
#include <RRC_TDD-UL-DL-ConfigDedicated.h>
#include <RRC_TDD-UL-DL-Pattern.h>
#include <RRC_TDD-UL-DL-SlotConfig.h>
#include <RRC_TDD-UL-DL-SlotIndex.h>
#include <RRC_ThresholdNR.h>
#include <RRC_TimeAlignmentTimer.h>
#include <RRC_TimeToTrigger.h>
#include <RRC_T-PollRetransmit.h>
#include <RRC_TrackingAreaCode.h>
#include <RRC_T-Reassembly.h>
#include <RRC_T-Reselection.h>
#include <RRC_T-StatusProhibit.h>
#include <RRC_UAC-AccessCategory1-SelectionAssistanceInfo.h>
#include <RRC_UAC-BarringInfoSet.h>
#include <RRC_UAC-BarringInfoSetIndex.h>
#include <RRC_UAC-BarringInfoSetList.h>
#include <RRC_UAC-BarringPerCat.h>
#include <RRC_UAC-BarringPerCatList.h>
#include <RRC_UAC-BarringPerPLMN.h>
#include <RRC_UAC-BarringPerPLMN-List.h>
#include <RRC_UCI-OnPUSCH.h>
#include <RRC_UEAssistanceInformation.h>
#include <RRC_UEAssistanceInformation-IEs.h>
#include <RRC_UEAssistanceInformation-v1540-IEs.h>
#include <RRC_UECapabilityEnquiry.h>
#include <RRC_UECapabilityEnquiry-IEs.h>
#include <RRC_UECapabilityEnquiry-v1560-IEs.h>
#include <RRC_UECapabilityInformation.h>
#include <RRC_UECapabilityInformation-IEs.h>
#include <RRC_UE-CapabilityRAT-Container.h>
#include <RRC_UE-CapabilityRAT-ContainerList.h>
#include <RRC_UE-CapabilityRAT-Request.h>
#include <RRC_UE-CapabilityRAT-RequestList.h>
#include <RRC_UE-CapabilityRequestFilterCommon.h>
#include <RRC_UE-CapabilityRequestFilterNR.h>
#include <RRC_UE-CapabilityRequestFilterNR-v1540.h>
#include <RRC_UE-MRDC-CapabilityAddFRX-Mode.h>
#include <RRC_UE-MRDC-CapabilityAddXDD-Mode.h>
#include <RRC_UE-MRDC-CapabilityAddXDD-Mode-v1560.h>
#include <RRC_UE-MRDC-Capability.h>
#include <RRC_UE-MRDC-Capability-v1560.h>
#include <RRC_UE-NR-CapabilityAddFRX-Mode.h>
#include <RRC_UE-NR-CapabilityAddFRX-Mode-v1540.h>
#include <RRC_UE-NR-CapabilityAddXDD-Mode.h>
#include <RRC_UE-NR-CapabilityAddXDD-Mode-v1530.h>
#include <RRC_UE-NR-Capability.h>
#include <RRC_UE-NR-Capability-v1530.h>
#include <RRC_UE-NR-Capability-v1540.h>
#include <RRC_UE-NR-Capability-v1550.h>
#include <RRC_UE-NR-Capability-v1560.h>
#include <RRC_UERadioAccessCapabilityInformation.h>
#include <RRC_UERadioAccessCapabilityInformation-IEs.h>
#include <RRC_UERadioPagingInformation.h>
#include <RRC_UERadioPagingInformation-IEs.h>
#include <RRC_UE-TimersAndConstants.h>
#include <RRC_UL-AM-RLC.h>
#include <RRC_UL-CCCH1-Message.h>
#include <RRC_UL-CCCH1-MessageType.h>
#include <RRC_UL-CCCH-Message.h>
#include <RRC_UL-CCCH-MessageType.h>
#include <RRC_UL-DataSplitThreshold.h>
#include <RRC_UL-DCCH-Message.h>
#include <RRC_UL-DCCH-MessageType.h>
#include <RRC_ULInformationTransfer.h>
#include <RRC_ULInformationTransfer-IEs.h>
#include <RRC_ULInformationTransferMRDC.h>
#include <RRC_ULInformationTransferMRDC-IEs.h>
#include <RRC_UL-UM-RLC.h>
#include <RRC_UplinkConfigCommon.h>
#include <RRC_UplinkConfigCommonSIB.h>
#include <RRC_UplinkConfig.h>
#include <RRC_UplinkTxDirectCurrentBWP.h>
#include <RRC_UplinkTxDirectCurrentCell.h>
#include <RRC_UplinkTxDirectCurrentList.h>
#include <RRC_VarMeasConfig.h>
#include <RRC_VarMeasReport.h>
#include <RRC_VarMeasReportList.h>
#include <RRC_VarPendingRNA-Update.h>
#include <RRC_VarResumeMAC-Input.h>
#include <RRC_VarShortMAC-Input.h>
#include <RRC_VictimSystemType.h>
#include <RRC_ZP-CSI-RS-Resource.h>
#include <RRC_ZP-CSI-RS-ResourceId.h>
#include <RRC_ZP-CSI-RS-ResourceSet.h>
#include <RRC_ZP-CSI-RS-ResourceSetId.h>
