/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "NGAP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-OER -gen-PER -no-gen-example -D ngap`
 */

#ifndef	_ASN_NGAP_ProtocolIE_Container_H_
#define	_ASN_NGAP_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_NGAP_MBSSessionSetupOrModRequestTransferIEs;
struct ASN_NGAP_MulticastSessionUpdateRequestTransferIEs;
struct ASN_NGAP_PDUSessionResourceModifyRequestTransferIEs;
struct ASN_NGAP_PDUSessionResourceSetupRequestTransferIEs;
struct ASN_NGAP_PDUSessionResourceSetupRequestIEs;
struct ASN_NGAP_PDUSessionResourceSetupResponseIEs;
struct ASN_NGAP_PDUSessionResourceReleaseCommandIEs;
struct ASN_NGAP_PDUSessionResourceReleaseResponseIEs;
struct ASN_NGAP_PDUSessionResourceModifyRequestIEs;
struct ASN_NGAP_PDUSessionResourceModifyResponseIEs;
struct ASN_NGAP_PDUSessionResourceNotifyIEs;
struct ASN_NGAP_PDUSessionResourceModifyIndicationIEs;
struct ASN_NGAP_PDUSessionResourceModifyConfirmIEs;
struct ASN_NGAP_InitialContextSetupRequestIEs;
struct ASN_NGAP_InitialContextSetupResponseIEs;
struct ASN_NGAP_InitialContextSetupFailureIEs;
struct ASN_NGAP_UEContextReleaseRequest_IEs;
struct ASN_NGAP_UEContextReleaseCommand_IEs;
struct ASN_NGAP_UEContextReleaseComplete_IEs;
struct ASN_NGAP_UEContextResumeRequestIEs;
struct ASN_NGAP_UEContextResumeResponseIEs;
struct ASN_NGAP_UEContextResumeFailureIEs;
struct ASN_NGAP_UEContextSuspendRequestIEs;
struct ASN_NGAP_UEContextSuspendResponseIEs;
struct ASN_NGAP_UEContextSuspendFailureIEs;
struct ASN_NGAP_UEContextModificationRequestIEs;
struct ASN_NGAP_UEContextModificationResponseIEs;
struct ASN_NGAP_UEContextModificationFailureIEs;
struct ASN_NGAP_RRCInactiveTransitionReportIEs;
struct ASN_NGAP_RetrieveUEInformationIEs;
struct ASN_NGAP_UEInformationTransferIEs;
struct ASN_NGAP_RANCPRelocationIndicationIEs;
struct ASN_NGAP_HandoverRequiredIEs;
struct ASN_NGAP_HandoverCommandIEs;
struct ASN_NGAP_HandoverPreparationFailureIEs;
struct ASN_NGAP_HandoverRequestIEs;
struct ASN_NGAP_HandoverRequestAcknowledgeIEs;
struct ASN_NGAP_HandoverFailureIEs;
struct ASN_NGAP_HandoverNotifyIEs;
struct ASN_NGAP_PathSwitchRequestIEs;
struct ASN_NGAP_PathSwitchRequestAcknowledgeIEs;
struct ASN_NGAP_PathSwitchRequestFailureIEs;
struct ASN_NGAP_HandoverCancelIEs;
struct ASN_NGAP_HandoverCancelAcknowledgeIEs;
struct ASN_NGAP_HandoverSuccessIEs;
struct ASN_NGAP_UplinkRANEarlyStatusTransferIEs;
struct ASN_NGAP_DownlinkRANEarlyStatusTransferIEs;
struct ASN_NGAP_UplinkRANStatusTransferIEs;
struct ASN_NGAP_DownlinkRANStatusTransferIEs;
struct ASN_NGAP_PagingIEs;
struct ASN_NGAP_InitialUEMessage_IEs;
struct ASN_NGAP_DownlinkNASTransport_IEs;
struct ASN_NGAP_UplinkNASTransport_IEs;
struct ASN_NGAP_NASNonDeliveryIndication_IEs;
struct ASN_NGAP_RerouteNASRequest_IEs;
struct ASN_NGAP_NGSetupRequestIEs;
struct ASN_NGAP_NGSetupResponseIEs;
struct ASN_NGAP_NGSetupFailureIEs;
struct ASN_NGAP_RANConfigurationUpdateIEs;
struct ASN_NGAP_RANConfigurationUpdateAcknowledgeIEs;
struct ASN_NGAP_RANConfigurationUpdateFailureIEs;
struct ASN_NGAP_AMFConfigurationUpdateIEs;
struct ASN_NGAP_AMFConfigurationUpdateAcknowledgeIEs;
struct ASN_NGAP_AMFConfigurationUpdateFailureIEs;
struct ASN_NGAP_AMFStatusIndicationIEs;
struct ASN_NGAP_NGResetIEs;
struct ASN_NGAP_NGResetAcknowledgeIEs;
struct ASN_NGAP_ErrorIndicationIEs;
struct ASN_NGAP_OverloadStartIEs;
struct ASN_NGAP_OverloadStopIEs;
struct ASN_NGAP_UplinkRANConfigurationTransferIEs;
struct ASN_NGAP_DownlinkRANConfigurationTransferIEs;
struct ASN_NGAP_WriteReplaceWarningRequestIEs;
struct ASN_NGAP_WriteReplaceWarningResponseIEs;
struct ASN_NGAP_PWSCancelRequestIEs;
struct ASN_NGAP_PWSCancelResponseIEs;
struct ASN_NGAP_PWSRestartIndicationIEs;
struct ASN_NGAP_PWSFailureIndicationIEs;
struct ASN_NGAP_DownlinkUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_UplinkUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_UplinkNonUEAssociatedNRPPaTransportIEs;
struct ASN_NGAP_TraceStartIEs;
struct ASN_NGAP_TraceFailureIndicationIEs;
struct ASN_NGAP_DeactivateTraceIEs;
struct ASN_NGAP_CellTrafficTraceIEs;
struct ASN_NGAP_LocationReportingControlIEs;
struct ASN_NGAP_LocationReportingFailureIndicationIEs;
struct ASN_NGAP_LocationReportIEs;
struct ASN_NGAP_UETNLABindingReleaseRequestIEs;
struct ASN_NGAP_UERadioCapabilityInfoIndicationIEs;
struct ASN_NGAP_UERadioCapabilityCheckRequestIEs;
struct ASN_NGAP_UERadioCapabilityCheckResponseIEs;
struct ASN_NGAP_SecondaryRATDataUsageReportIEs;
struct ASN_NGAP_UplinkRIMInformationTransferIEs;
struct ASN_NGAP_DownlinkRIMInformationTransferIEs;
struct ASN_NGAP_ConnectionEstablishmentIndicationIEs;
struct ASN_NGAP_UERadioCapabilityIDMappingRequestIEs;
struct ASN_NGAP_UERadioCapabilityIDMappingResponseIEs;
struct ASN_NGAP_AMFCPRelocationIndicationIEs;
struct ASN_NGAP_BroadcastSessionSetupRequestIEs;
struct ASN_NGAP_BroadcastSessionSetupResponseIEs;
struct ASN_NGAP_BroadcastSessionSetupFailureIEs;
struct ASN_NGAP_BroadcastSessionModificationRequestIEs;
struct ASN_NGAP_BroadcastSessionModificationResponseIEs;
struct ASN_NGAP_BroadcastSessionModificationFailureIEs;
struct ASN_NGAP_BroadcastSessionReleaseRequestIEs;
struct ASN_NGAP_BroadcastSessionReleaseRequiredIEs;
struct ASN_NGAP_BroadcastSessionReleaseResponseIEs;
struct ASN_NGAP_DistributionSetupRequestIEs;
struct ASN_NGAP_DistributionSetupResponseIEs;
struct ASN_NGAP_DistributionSetupFailureIEs;
struct ASN_NGAP_DistributionReleaseRequestIEs;
struct ASN_NGAP_DistributionReleaseResponseIEs;
struct ASN_NGAP_MulticastSessionActivationRequestIEs;
struct ASN_NGAP_MulticastSessionActivationResponseIEs;
struct ASN_NGAP_MulticastSessionActivationFailureIEs;
struct ASN_NGAP_MulticastSessionDeactivationRequestIEs;
struct ASN_NGAP_MulticastSessionDeactivationResponseIEs;
struct ASN_NGAP_MulticastSessionUpdateRequestIEs;
struct ASN_NGAP_MulticastSessionUpdateResponseIEs;
struct ASN_NGAP_MulticastSessionUpdateFailureIEs;
struct ASN_NGAP_MulticastGroupPagingIEs;

/* ASN_NGAP_ProtocolIE-Container */
typedef struct ASN_NGAP_ProtocolIE_Container_123P0 {
	A_SEQUENCE_OF(struct ASN_NGAP_MBSSessionSetupOrModRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P0_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P1 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionUpdateRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P1_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P2 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P2_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P3 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceSetupRequestTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P3_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P4 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P4_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P5 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P5_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P6 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P6_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P7 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P7_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P8 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P8_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P9 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P9_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P10 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P10_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P11 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P11_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P12 {
	A_SEQUENCE_OF(struct ASN_NGAP_PDUSessionResourceModifyConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P12_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P13 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P13_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P14 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P14_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P15 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P15_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P16 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P16_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P17 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P17_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P18 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P18_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P19 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextResumeRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P19_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P20 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextResumeResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P20_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P21 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextResumeFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P21_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P22 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextSuspendRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P22_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P23 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextSuspendResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P23_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P24 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextSuspendFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P24_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P25 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P25_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P26 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P26_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P27 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P27_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P28 {
	A_SEQUENCE_OF(struct ASN_NGAP_RRCInactiveTransitionReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P28_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P29 {
	A_SEQUENCE_OF(struct ASN_NGAP_RetrieveUEInformationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P29_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P30 {
	A_SEQUENCE_OF(struct ASN_NGAP_UEInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P30_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P31 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P31_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P32 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P32_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P33 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P33_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P34 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P34_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P35 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P35_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P36 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P36_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P37 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P37_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P38 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P38_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P39 {
	A_SEQUENCE_OF(struct ASN_NGAP_PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P39_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P40 {
	A_SEQUENCE_OF(struct ASN_NGAP_PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P40_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P41 {
	A_SEQUENCE_OF(struct ASN_NGAP_PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P41_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P42 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P42_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P43 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P43_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P44 {
	A_SEQUENCE_OF(struct ASN_NGAP_HandoverSuccessIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P44_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P45 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P45_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P46 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRANEarlyStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P46_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P47 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P47_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P48 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRANStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P48_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P49 {
	A_SEQUENCE_OF(struct ASN_NGAP_PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P49_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P50 {
	A_SEQUENCE_OF(struct ASN_NGAP_InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P50_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P51 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P51_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P52 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P52_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P53 {
	A_SEQUENCE_OF(struct ASN_NGAP_NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P53_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P54 {
	A_SEQUENCE_OF(struct ASN_NGAP_RerouteNASRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P54_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P55 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P55_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P56 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P56_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P57 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P57_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P58 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P58_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P59 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P59_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P60 {
	A_SEQUENCE_OF(struct ASN_NGAP_RANConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P60_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P61 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P61_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P62 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P62_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P63 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P63_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P64 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFStatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P64_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P65 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P65_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P66 {
	A_SEQUENCE_OF(struct ASN_NGAP_NGResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P66_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P67 {
	A_SEQUENCE_OF(struct ASN_NGAP_ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P67_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P68 {
	A_SEQUENCE_OF(struct ASN_NGAP_OverloadStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P68_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P69 {
	A_SEQUENCE_OF(struct ASN_NGAP_OverloadStopIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P69_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P70 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P70_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P71 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRANConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P71_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P72 {
	A_SEQUENCE_OF(struct ASN_NGAP_WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P72_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P73 {
	A_SEQUENCE_OF(struct ASN_NGAP_WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P73_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P74 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSCancelRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P74_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P75 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSCancelResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P75_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P76 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P76_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P77 {
	A_SEQUENCE_OF(struct ASN_NGAP_PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P77_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P78 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P78_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P79 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P79_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P80 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P80_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P81 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkNonUEAssociatedNRPPaTransportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P81_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P82 {
	A_SEQUENCE_OF(struct ASN_NGAP_TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P82_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P83 {
	A_SEQUENCE_OF(struct ASN_NGAP_TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P83_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P84 {
	A_SEQUENCE_OF(struct ASN_NGAP_DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P84_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P85 {
	A_SEQUENCE_OF(struct ASN_NGAP_CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P85_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P86 {
	A_SEQUENCE_OF(struct ASN_NGAP_LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P86_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P87 {
	A_SEQUENCE_OF(struct ASN_NGAP_LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P87_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P88 {
	A_SEQUENCE_OF(struct ASN_NGAP_LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P88_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P89 {
	A_SEQUENCE_OF(struct ASN_NGAP_UETNLABindingReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P89_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P90 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P90_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P91 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P91_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P92 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityCheckResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P92_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P93 {
	A_SEQUENCE_OF(struct ASN_NGAP_SecondaryRATDataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P93_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P94 {
	A_SEQUENCE_OF(struct ASN_NGAP_UplinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P94_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P95 {
	A_SEQUENCE_OF(struct ASN_NGAP_DownlinkRIMInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P95_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P96 {
	A_SEQUENCE_OF(struct ASN_NGAP_ConnectionEstablishmentIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P96_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P97 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityIDMappingRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P97_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P98 {
	A_SEQUENCE_OF(struct ASN_NGAP_UERadioCapabilityIDMappingResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P98_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P99 {
	A_SEQUENCE_OF(struct ASN_NGAP_AMFCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P99_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P100 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P100_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P101 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P101_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P102 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P102_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P103 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P103_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P104 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P104_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P105 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P105_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P106 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P106_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P107 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionReleaseRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P107_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P108 {
	A_SEQUENCE_OF(struct ASN_NGAP_BroadcastSessionReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P108_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P109 {
	A_SEQUENCE_OF(struct ASN_NGAP_DistributionSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P109_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P110 {
	A_SEQUENCE_OF(struct ASN_NGAP_DistributionSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P110_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P111 {
	A_SEQUENCE_OF(struct ASN_NGAP_DistributionSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P111_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P112 {
	A_SEQUENCE_OF(struct ASN_NGAP_DistributionReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P112_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P113 {
	A_SEQUENCE_OF(struct ASN_NGAP_DistributionReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P113_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P114 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionActivationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P114_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P115 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionActivationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P115_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P116 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionActivationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P116_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P117 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionDeactivationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P117_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P118 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionDeactivationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P118_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P119 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionUpdateRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P119_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P120 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionUpdateResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P120_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P121 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastSessionUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P121_t;
typedef struct ASN_NGAP_ProtocolIE_Container_123P122 {
	A_SEQUENCE_OF(struct ASN_NGAP_MulticastGroupPagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_NGAP_ProtocolIE_Container_123P122_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P0;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P0_1[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P1;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P1_3[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P2;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P2_5[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P3;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P3_7[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P4;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P4_9[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P5;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P5_11[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P6;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P6_13[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P7;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P7_15[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P8;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P8_17[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P9;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P9_19[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P10;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P10_21[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P11;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P11_23[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P12;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P12_25[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P13;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P13_27[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P14;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P14_29[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P15;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P15_31[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P16;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P16_33[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P17;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P17_35[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P18;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P18_37[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P19;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P19_39[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P20;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P20_41[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P21;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P21_43[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P22;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P22_45[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P23;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P23_47[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P24;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P24_49[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P25;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P25_51[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P26;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P26_53[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P27;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P27_55[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P28;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P28_57[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P29;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P29_59[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P30;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P30_61[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P31;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P31_63[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P32;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P32_65[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P33;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P33_67[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P34;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P34_69[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P35;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P35_71[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P36;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P36_73[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P37;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P37_75[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P38;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P38_77[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P39;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P39_79[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P40;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P40_81[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P41;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P41_83[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P42;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P42_85[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P43;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P43_87[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P44;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P44_89[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P45;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P45_91[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P46;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P46_93[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P47;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P47_95[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P48;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P48_97[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P49;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P49_99[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P50;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P50_101[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P51;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P51_103[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P52;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P52_105[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P53;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P53_107[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P54;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P54_109[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P55;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P55_111[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P56;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P56_113[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P57;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P57_115[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P58;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P58_117[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P59;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P59_119[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P60;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P60_121[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P61;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P61_123[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P62;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P62_125[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P63;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P63_127[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P64;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P64_129[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P65;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P65_131[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P66;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P66_133[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P67;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P67_135[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P68;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P68_137[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P69;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P69_139[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P70;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P70_141[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P71;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P71_143[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P72;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P72_145[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P73;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P73_147[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P74;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P74_149[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P75;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P75_151[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P76;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P76_153[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P77;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P77_155[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P78;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P78_157[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P79;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P79_159[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P80;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P80_161[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P81;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P81_163[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P82;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P82_165[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P83;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P83_167[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P84;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P84_169[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P85;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P85_171[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P86;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P86_173[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P87;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P87_175[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P88;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P88_177[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P89;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P89_179[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P90;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P90_181[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P91;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P91_183[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P92;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P92_specs_185;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P92_185[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P93;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P93_specs_187;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P93_187[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P94;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P94_specs_189;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P94_189[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P95;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P95_specs_191;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P95_191[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P96;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P96_specs_193;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P96_193[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P97;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P97_specs_195;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P97_195[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P98;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P98_specs_197;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P98_197[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P99;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P99_specs_199;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P99_199[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P100;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P100_specs_201;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P100_201[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P101;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P101_specs_203;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P101_203[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P101_constr_203;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P102;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P102_specs_205;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P102_205[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P102_constr_205;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P103;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P103_specs_207;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P103_207[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P103_constr_207;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P104;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P104_specs_209;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P104_209[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P104_constr_209;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P105;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P105_specs_211;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P105_211[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P105_constr_211;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P106;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P106_specs_213;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P106_213[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P106_constr_213;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P107;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P107_specs_215;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P107_215[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P107_constr_215;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P108;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P108_specs_217;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P108_217[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P108_constr_217;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P109;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P109_specs_219;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P109_219[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P109_constr_219;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P110;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P110_specs_221;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P110_221[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P110_constr_221;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P111;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P111_specs_223;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P111_223[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P111_constr_223;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P112;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P112_specs_225;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P112_225[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P112_constr_225;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P113;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P113_specs_227;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P113_227[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P113_constr_227;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P114;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P114_specs_229;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P114_229[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P114_constr_229;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P115;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P115_specs_231;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P115_231[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P115_constr_231;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P116;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P116_specs_233;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P116_233[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P116_constr_233;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P117;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P117_specs_235;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P117_235[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P117_constr_235;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P118;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P118_specs_237;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P118_237[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P118_constr_237;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P119;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P119_specs_239;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P119_239[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P119_constr_239;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P120;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P120_specs_241;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P120_241[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P120_constr_241;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P121;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P121_specs_243;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P121_243[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P121_constr_243;
extern asn_TYPE_descriptor_t asn_DEF_ASN_NGAP_ProtocolIE_Container_123P122;
extern asn_SET_OF_specifics_t asn_SPC_ASN_NGAP_ProtocolIE_Container_123P122_specs_245;
extern asn_TYPE_member_t asn_MBR_ASN_NGAP_ProtocolIE_Container_123P122_245[1];
extern asn_per_constraints_t asn_PER_type_ASN_NGAP_ProtocolIE_Container_123P122_constr_245;

#ifdef __cplusplus
}
#endif

#endif	/* _ASN_NGAP_ProtocolIE_Container_H_ */
#include <asn_internal.h>
